Repository awslabs/gluonts, pull requests merged in 2020-11, with the labels that each got.

#1137 Masking edge case fix
  src/gluonts/transform/feature.py
  test/test_transform.py
Labels: backport v0.6.x

#1159 Fix edge case for `cyclic`
  src/gluonts/itertools.py
  test/test_itertools.py
Labels: pending v0.6.x backport

#1173 Added item_id to NPTS and Naive2 forecasts
  src/gluonts/model/naive_2/_predictor.py
  src/gluonts/model/npts/_model.py
  src/gluonts/model/npts/_predictor.py
Labels: pending v0.6.x backport

#1171 fixes in dataset mutability
  src/gluonts/transform/feature.py
  test/test_dataset_mutability.py
Labels: pending v0.6.x backport

#1178 Remove input_names argument to trainer __call__
  src/gluonts/model/estimator.py
  src/gluonts/model/wavenet/_estimator.py
  src/gluonts/mx/trainer/_base.py
Labels: BREAKING
