Repository awslabs/gluonts, pull requests merged in 2021-09, with the labels that each got.

#1665 Hierarchical Forecaster: End-to-End model based on DeepVAR
  src/gluonts/model/deepvar/_estimator.py
  src/gluonts/model/deepvar/_network.py
  src/gluonts/model/deepvar_hierarchical/.typesafe
  src/gluonts/model/deepvar_hierarchical/__init__.py
  src/gluonts/model/deepvar_hierarchical/_estimator.py
  src/gluonts/model/deepvar_hierarchical/_network.py
  src/gluonts/model/gpvar/_estimator.py
  src/gluonts/mx/distribution/__init__.py
  src/gluonts/mx/distribution/distribution.py
  src/gluonts/mx/distribution/empirical_distribution.py
  src/gluonts/mx/distribution/lowrank_multivariate_gaussian.py
  test/distribution/test_distribution_methods.py
  test/distribution/test_distribution_output_serde.py
  test/distribution/test_distribution_shapes.py
  test/distribution/test_mx_distribution_inference.py
  test/model/deepvar_hierarchical/generate_hierarchical_dataset.py
  test/model/deepvar_hierarchical/test_deepvar_hierarchical.py
Labels: new feature

#1699 Fixing doc build from mqcnn-iqf commit
  src/gluonts/model/forecast.py
  src/gluonts/model/seq2seq/_transform.py
  src/gluonts/mx/block/quantile_output.py
  src/gluonts/support/util.py
  test/support/test_util.py
Labels: documentation, other change

#1702 Fix scaling for pytorch negative binomial output
  src/gluonts/torch/modules/distribution_output.py
Labels: bug fix
