Repository awslabs/gluonts, pull requests merged in 2021-07, with the labels that each got.

#1601 add GitHub workflow for publishing to PyPI for new releases
  .github/workflows/pypi.yml
Labels: dev setup

#1602 add dummy estimator to trivial models
  src/gluonts/model/trivial/_estimator.py
Labels: new feature

#1604 loosen RTOL in `test/distribution/test_flows.py` to make `test_flow_invertibility` pass
  test/distribution/test_flows.py
Labels: other change, pending v0.8.x backport

#1612 Move callbacks example to docs
  docs/tutorials/index.rst
  docs/tutorials/mxnet_models/trainer_callbacks.md
  examples/callbacks_example.ipynb
  src/gluonts/mx/__init__.py
Labels: other change

#1624 Add serde module doc.
  src/gluonts/core/serde/__init__.py
Labels: other change

#1632 Add additional datasets from the Monash Time Series Forecasting Repository
  src/gluonts/dataset/repository/_artificial.py
  src/gluonts/dataset/repository/_gp_copula_2019.py
  src/gluonts/dataset/repository/_lstnet.py
  src/gluonts/dataset/repository/_m3.py
  src/gluonts/dataset/repository/_tsf_datasets.py
  src/gluonts/dataset/repository/_tsf_reader.py
  src/gluonts/dataset/repository/datasets.py
Labels: bug fix, enhancement
