Repository awslabs/gluonts, pull requests merged in 2021-12, with the labels that each got.

#1746 Adding ISQF distribution class
  src/gluonts/mx/distribution/__init__.py
  src/gluonts/mx/distribution/isqf.py
  test/distribution/test_isqf.py
  test/model/seq2seq/test_model.py
Labels: new feature

#1809 Fixed data leakage bug in implementation of dynamic real and categorical features
  src/gluonts/model/rotbaum/_preprocess.py
Labels: bug fix

#1811 added a readme notebook for LSF
  src/gluonts/model/rotbaum/README_LSF.ipynb
  src/gluonts/model/rotbaum/_model.py
Labels: documentation

#1820 added missing word in readme
  src/gluonts/model/rotbaum/README_LSF.ipynb
Labels: documentation
