Repository awslabs/gluonts, pull requests merged in 2021-11, with the labels that each got.

#1765 upgrade pytorch and pytorch-lightning requirements and some fixes
  .github/workflows/mxnet_nightly.yml
  .github/workflows/test_release_unix_nightly.yml
  .github/workflows/test_release_win32_nightly.yml
  .github/workflows/tests.yml
  docs/tutorials/forecasting/howto_pytorch_lightning.md
  requirements/requirements-pytorch.txt
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/estimator.py
  src/gluonts/torch/model/predictor.py
  test/torch/model/test_simple_torch_model.py
Labels: bug fix, other change

#1763 Add CODEOWNERS.
  CODEOWNERS
Labels: other change

#1752 fix torch NOPScaler shape
  src/gluonts/torch/modules/scaler.py
  test/torch/model/test_deepar_modules.py
Labels: bug fix

#1735 Add number of downloads to readme.md
  README.md
Labels: other change

#1779 fix for #1725, bugs in deep renewal process
  src/gluonts/model/renewal/_estimator.py
  src/gluonts/model/renewal/_network.py
  test/model/renewal/test_predictor.py
Labels: bug fix

#1792 Remove support module.
  examples/persist_model.py
  src/gluonts/dataset/repository/_lstnet.py
  src/gluonts/dataset/repository/datasets.py
  src/gluonts/dataset/util.py
  src/gluonts/evaluation/backtest.py
  src/gluonts/itertools.py
  src/gluonts/model/canonical/_estimator.py
  src/gluonts/model/deep_factor/_estimator.py
  src/gluonts/model/deepar/_estimator.py
  src/gluonts/model/deepstate/_estimator.py
  src/gluonts/model/deepvar/_estimator.py
  src/gluonts/model/forecast.py
  src/gluonts/model/gp_forecaster/_estimator.py
  src/gluonts/model/gpvar/_estimator.py
  src/gluonts/model/lstnet/_estimator.py
  src/gluonts/model/n_beats/_estimator.py
  src/gluonts/model/naive_2/_predictor.py
  src/gluonts/model/r_forecast/_predictor.py
  src/gluonts/model/renewal/_estimator.py
  src/gluonts/model/rotbaum/_predictor.py
  src/gluonts/model/san/_estimator.py
  src/gluonts/model/seasonal_naive/_predictor.py
  src/gluonts/model/seq2seq/_forking_estimator.py
  src/gluonts/model/seq2seq/_seq2seq_estimator.py
  src/gluonts/model/simple_feedforward/_estimator.py
  src/gluonts/model/tft/_estimator.py
  src/gluonts/model/tpp/deeptpp/_estimator.py
  src/gluonts/model/transformer/_estimator.py
  src/gluonts/model/trivial/constant.py
  src/gluonts/model/trivial/identity.py
  src/gluonts/model/trivial/mean.py
  src/gluonts/model/util.py
  src/gluonts/model/wavenet/_estimator.py
  src/gluonts/mx/batchify.py
  src/gluonts/shell/env.py
  src/gluonts/shell/sagemaker/params.py
  src/gluonts/shell/train.py
  src/gluonts/support/.typesafe
  src/gluonts/support/__init__.py
  src/gluonts/support/pandas.py
  src/gluonts/transform/convert.py
  test/dataset/test_dataset_mutability.py
  test/dataset/test_dataset_types.py
  test/model/naive_predictors/test_predictors.py
  test/model/r_forecast/test_r_predictor.py
  test/model/test_util.py
  test/mx/test_mx_util.py
  test/mx/trainer/.typesafe
  test/mx/trainer/test_callbacks.py
  test/mx/trainer/test_learning_rate_scheduler.py
  test/mx/trainer/test_model_averaging.py
  test/mx/trainer/test_model_iteration_averaging.py
  test/mx/trainer/test_trainer.py
  test/test_forecaster_entrypoints.py
  test/test_json.py
  test/test_transform.py
Labels: BREAKING

#1800 Remove mxnet dependency from data-loader tests.
  .gitignore
  src/gluonts/core/component.py
  src/gluonts/core/serde/np.py
  src/gluonts/testutil/batchify.py
  test/conftest.py
  test/dataset/test_data_loader.py
  test/mx/test_jitter.py
  test/mx/test_variable_length.py
  test/test_transform.py
Labels: tests
