Repository awslabs/gluonts, pull requests merged in 2021-06, with the labels that each got.

#1495 Loader simplification
  src/gluonts/dataset/loader.py
  src/gluonts/model/renewal/_estimator.py
Labels: other change

#1519 Serde: Allow encoding of functions and methods.
  src/gluonts/core/_base.py
  src/gluonts/core/serde/_base.py
  test/core/test_serde.py
Labels: enhancement

#1535 fix ProphetPredictor serialization issue
  src/gluonts/model/prophet/_predictor.py
  test/model/prophet/test_prophet.py
Labels: bug fix, pending v0.7.x backport

#1537 Add item_id to r forecast predictors
  src/gluonts/model/r_forecast/_predictor.py
Labels: bug fix, pending v0.7.x backport

#1543 Fix serde issue with some distribution output types
  src/gluonts/mx/distribution/neg_binomial.py
  src/gluonts/mx/distribution/poisson.py
  test/distribution/test_distribution_output_serde.py
Labels: bug fix, pending v0.7.x backport

#1544 QRX fixes and added functionality
  src/gluonts/model/rotbaum/_model.py
  src/gluonts/model/rotbaum/_predictor.py
  src/gluonts/model/rotbaum/_preprocess.py
  src/gluonts/nursery/QRX-Wrapped-M5-Accuracy-Solution/0. README.md
  src/gluonts/nursery/QRX-Wrapped-M5-Accuracy-Solution/3. code/2. train/1-1. recursive_store_TRAIN.ipynb
  src/gluonts/nursery/QRX-Wrapped-M5-Accuracy-Solution/3. code/2. train/1-2. recursive_store_cat_TRAIN.ipynb
  src/gluonts/nursery/QRX-Wrapped-M5-Accuracy-Solution/3. code/2. train/1-3. recursive_store_dept_TRAIN.ipynb
  src/gluonts/nursery/QRX-Wrapped-M5-Accuracy-Solution/3. code/2. train/2-1. nonrecursive_store_TRAIN.ipynb
  src/gluonts/nursery/QRX-Wrapped-M5-Accuracy-Solution/3. code/2. train/2-2. nonrecursive_store_cat_TRAIN.ipynb
  src/gluonts/nursery/QRX-Wrapped-M5-Accuracy-Solution/3. code/2. train/2-3. nonrecursive_store_dept_TRAIN.ipynb
Labels: BREAKING, bug fix, model accuracy, new feature

#1552 Fixed bug: ".values()" to ".values"
  src/gluonts/model/rotbaum/_model.py
Labels: BREAKING, bug fix

#1555 Rename flake8 action step.
  .github/workflows/flake8.yml
Labels: CI, other change

#1538 Extend FileDataset's Parameters to load_datasets
  src/gluonts/dataset/common.py
Labels: new feature

#1564 R fixes for methods that produce point forecasts or prediction intervals directly
  src/gluonts/model/r_forecast/R/forecast_methods.R
  src/gluonts/model/r_forecast/__init__.py
  src/gluonts/model/r_forecast/_predictor.py
  test/model/r_forecast/test_r_predictor.py
Labels: bug fix

#1568 Add STL-AR as one more R baseline model
  src/gluonts/model/r_forecast/R/forecast_methods.R
  src/gluonts/model/r_forecast/_predictor.py
Labels: enhancement

#1557 Fix computation of OWA
  src/gluonts/evaluation/_base.py
  src/gluonts/evaluation/backtest.py
  src/gluonts/evaluation/metrics.py
  test/evaluation/test_evaluator.py
  test/evaluation/test_metrics.py
  test/model/naive_predictors/test_predictors.py
Labels: bug fix

#1574 Delete pytorch_predictor_example.ipynb
  examples/pytorch_predictor_example.ipynb
Labels: documentation, other change

#1586 Mark torch distribution inference tests as flaky
  test/torch/modules/test_torch_distribution_inference.py
Labels: other change

#1562 Allow validation data for TabularEstimator.
  src/gluonts/nursery/autogluon_tabular/estimator.py
  src/gluonts/nursery/autogluon_tabular/example.py
  test/nursery/test_autogluon_tabular.py
Labels: new feature

#1583 Update REFERENCES.md
  REFERENCES.md
Labels: other change

#1591 Fix single dispatch register for py36
  src/gluonts/nursery/glide/_partition.py
Labels: bug fix

#1593 Fix frequency in metadata for lstnet datasets
  src/gluonts/dataset/repository/_lstnet.py
Labels: bug fix

#1592 shallow import for `gluonts.mx` module
  docs/tutorials/forecasting/extended_tutorial.md
  docs/tutorials/forecasting/quick_start_tutorial.md
  src/gluonts/mx/__init__.py
Labels: other change
