Repository awslabs/gluonts, pull requests merged in 2021-05, with the labels that each got.

#1437 fix compatibility for pandas < 1.1 in `time_feature/_base.py`
  src/gluonts/time_feature/_base.py
Labels: pending v0.7.x backport

#1450 Fix missing import in `gluonts.mx.model.GluonEstimator`
  src/gluonts/mx/model/estimator.py
Labels: pending v0.7.x backport

#1168 Add callbacks mechanism to Trainer class
  examples/callbacks_example.ipynb
  src/gluonts/mx/trainer/_base.py
  src/gluonts/mx/trainer/callback.py
  src/gluonts/mx/trainer/learning_rate_scheduler.py
  src/gluonts/mx/trainer/model_averaging.py
  src/gluonts/mx/trainer/model_iteration_averaging.py
  test/model/deepvar/test_deepvar.py
  test/trainer/test_callbacks.py
  test/trainer/test_learning_rate_scheduler.py
  test/trainer/test_trainer.py
Labels: new feature

#1443 add label requirement information to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dev setup

#1456 Test on mxnet~=1.8.0 and torch==1.8.1, other fixes to workflows
  .github/workflows/mxnet_nightly.yml
  .github/workflows/style_type_checks.yml
  .github/workflows/test_release_unix_nightly.yml
  .github/workflows/test_release_win32_nightly.yml
  .github/workflows/tests.yml
  requirements/requirements-mxnet.txt
Labels: dev setup

#1457 Change miniver fallback version from `unknown` to `0.0.0`.
  src/gluonts/_version.py
Labels: bug fix

#1459 support Min freq for get_seasonality() method
  src/gluonts/time_feature/seasonality.py
  test/time_feature/test_seasonality.py
Labels: new feature

#1458 Deep renewal processes for intermittent demand forecasting
  src/gluonts/model/renewal/__init__.py
  src/gluonts/model/renewal/_estimator.py
  src/gluonts/model/renewal/_network.py
  src/gluonts/model/renewal/_predictor.py
  src/gluonts/model/renewal/_transform.py
  src/gluonts/transform/feature.py
  test/model/renewal/__init__.py
  test/model/renewal/test_model.py
  test/model/renewal/test_predictor.py
Labels: enhancement, new feature

#1494 `Transform.apply`
  src/gluonts/dataset/loader.py
  src/gluonts/evaluation/backtest.py
  src/gluonts/model/renewal/_estimator.py
  src/gluonts/mx/model/estimator.py
  src/gluonts/shell/train.py
  src/gluonts/transform/__init__.py
  src/gluonts/transform/_base.py
  src/gluonts/transform/dataset.py
  test/model/deepar/test_deepar_auxiliary_outputs.py
Labels: API change

#1501 Fix Settings._inject to check if it can provide the value.
  src/gluonts/core/settings.py
  test/core/test_settings.py
Labels: bug fix

#1504 Settings partial assignment
  src/gluonts/core/settings.py
  test/core/test_settings.py
Labels: new feature

#1515 Fix anomaly detection example
  examples/anomaly_detection.py
Labels: bug fix

#1516 Settings: Fix partial assignment.
  src/gluonts/core/settings.py
  test/core/test_settings.py
Labels: bug fix
