Repository awslabs/gluonts, pull requests merged in 2021-08, with the labels that each got.

#1645 Add batch_size attribute to MQCNNEstimator and MQRNNEstimator
  src/gluonts/model/seq2seq/_mq_dnn_estimator.py
Labels: pending v0.7.x backport, bug fix, pending v0.8.x backport

#1652 Fix frequency string conversion from ts format, add test
  src/gluonts/dataset/repository/_tsf_reader.py
  test/dataset/test_tsf_reader.py
Labels: bug fix, pending v0.8.x backport

#1651 Fix NegativeBinomial constructor args in NegativeBinomialOutput
  src/gluonts/torch/modules/distribution_output.py
  test/torch/modules/test_torch_distribution_inference.py
Labels: pending v0.7.x backport, bug fix, pending v0.8.x backport

#1658 Make Dataset runtime-checkable.
  src/gluonts/dataset/common.py
  test/dataset/test_common.py
Labels: other change

#1661 Cap numba<0.54, ipykernel<6.2.0
  requirements/requirements-docs.txt
  requirements/requirements-extras-anomaly-evaluation.txt
Labels: other change
