Repository awslabs/gluonts, pull requests merged in 2022-05, with the labels that each got.

#1946 Breaking: Split incremental quantile output into separate class
  src/gluonts/model/seq2seq/_mq_dnn_estimator.py
  src/gluonts/mx/block/quantile_output.py
  test/model/seq2seq/test_quantile_loss.py
  test/mx/block/test_quantile_loss.py
Labels: enhancement, BREAKING

#1965 Breaking: reorg torch package, shorten import paths
  docs/tutorials/forecasting/howto_pytorch_lightning.md
  examples/example_binned_pareto.py
  src/gluonts/torch/distributions/__init__.py
  src/gluonts/torch/distributions/binned_uniforms.py
  src/gluonts/torch/distributions/distribution_output.py
  src/gluonts/torch/distributions/generalized_pareto.py
  src/gluonts/torch/distributions/isqf.py
  src/gluonts/torch/distributions/mqf2.py
  src/gluonts/torch/distributions/piecewise_linear.py
  src/gluonts/torch/distributions/spliced_binned_pareto.py
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/model/mqf2/estimator.py
  src/gluonts/torch/model/mqf2/module.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/torch/model/simple_feedforward/module.py
  test/torch/distribution/test_torch_piecewise_linear.py
  test/torch/model/test_mqf2_modules.py
  test/torch/modules/test_torch_distribution_inference.py
Labels: BREAKING

#1962 Add support for beta-NLL loss
  src/gluonts/torch/distributions/__init__.py
  src/gluonts/torch/distributions/affine_transformed.py
  src/gluonts/torch/distributions/distribution_output.py
  src/gluonts/torch/modules/loss.py
  test/torch/model/test_estimators.py
Labels: new feature

#1968 Fix: use of num_parallel_samples in deepAR
  src/gluonts/torch/model/deepar/module.py
Labels: bug fix, pending v0.9.x backport

#1969 Fix: torch DeepAR observed indicator in multivariate case
  src/gluonts/torch/model/deepar/lightning_module.py
Labels: bug fix, pending v0.9.x backport

#1978 Update REFERENCES.md
  REFERENCES.md
Labels: other change

#1982 Add Uber-TLC dataset to dataset repository.
  src/gluonts/dataset/repository/_uber_tlc.py
  src/gluonts/dataset/repository/datasets.py
Labels: new feature

#1935 added support for pandas dataframes
  src/gluonts/dataset/dataframe.py
  test/dataset/test_dataframe.py
Labels: new feature

#1986 Fix OffsetSplitter for negative offsets
  src/gluonts/dataset/split/splitter.py
  test/dataset/split/test_split.py
Labels: bug fix, pending v0.9.x backport

#1990 Add info cli.
  src/gluonts/info.py
Labels: new feature

#1983 Documentation: add docstrings for torch-based models
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/deepar/lightning_module.py
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/torch/model/simple_feedforward/lightning_module.py
  src/gluonts/torch/model/simple_feedforward/module.py
Labels: documentation, other change
