Repository awslabs/gluonts, pull requests merged in 2022-04, with the labels that each got.

#1938 Fixed autograd inplace operations error in Transformed Distribution
  src/gluonts/mx/distribution/transformed_distribution.py
Labels: bug fix, pending v0.9.x backport

#1941 Breaking: Update dependency fbprophet -> prophet
  requirements/requirements-extras-prophet.txt
  src/gluonts/model/prophet/_predictor.py
  test/model/prophet/test_prophet.py
Labels: BREAKING

#1950 Fix: Hard threshold positive distribution parameters
  src/gluonts/mx/distribution/beta.py
  src/gluonts/mx/distribution/distribution_output.py
  src/gluonts/mx/distribution/gamma.py
  src/gluonts/mx/distribution/gaussian.py
  src/gluonts/mx/distribution/genpareto.py
  src/gluonts/mx/distribution/inflated_beta.py
  src/gluonts/mx/distribution/laplace.py
  src/gluonts/mx/distribution/logit_normal.py
  src/gluonts/mx/distribution/neg_binomial.py
  src/gluonts/mx/distribution/poisson.py
  src/gluonts/mx/distribution/student_t.py
Labels: bug fix, pending v0.9.x backport

#1952 Fix forecast keys (quantiles) output by TemporalFusionTransformer
  src/gluonts/model/tft/_estimator.py
  test/model/tft/test_model.py
Labels: bug fix, pending v0.9.x backport

#1958 Remove unnecessary lines in torch DeepAR network
  src/gluonts/torch/model/deepar/module.py
Labels: enhancement
