Repository awslabs/gluonts, pull requests merged in 2022-07, with the labels that each got.

#2135 Fix `DatasetCollection` for Python 3.9.
  src/gluonts/dataset/__init__.py
Labels: bug fix

#2144 Docs: Apply black to notebooks.
  docs/md2ipynb.py
  requirements/requirements-docs.txt
Labels: pr:docs-build-notebook

#2148 Make `PandasDataset` faster
  src/gluonts/dataset/pandas.py
Labels: bug fix, pending v0.10.x backport

#2131 Interrupting `mx.Trainer` stops training.
  src/gluonts/mx/trainer/_base.py
Labels: new feature, pending v0.10.x backport

#2150 Docs: Simplify wide `DataFrame` example
  docs/tutorials/data_manipulation/pandasdataframes.md.template
Labels: documentation, pending v0.10.x backport, pr:docs-build-notebook

#2149 Convert time-features into functions.
  src/gluonts/mx/model/deepstate/issm.py
  src/gluonts/mx/model/deepvar/_estimator.py
  src/gluonts/nursery/autogluon_tabular/predictor.py
  src/gluonts/time_feature/__init__.py
  src/gluonts/time_feature/_base.py
  test/model/conftest.py
  test/model/deepstate/test_issm.py
  test/mx/test_transform_equals.py
  test/nursery/autogluon_tabular/test_autogluon_tabular.py
  test/time_feature/test_features.py
  test/transform/test_add_time_features.py
  test/transform/test_transform.py
Labels: BREAKING

#2156 Docs: fix links in models table
  docs/getting_started/models.md
Labels: documentation, pending v0.10.x backport

#2129 Add 'Background' section to docs.
  docs/_static/electricity-10w.png
  docs/_static/forecast-distributions.png
  docs/getting_started/background.md
  docs/index.rst
Labels: documentation

#2161 Docs: Add info about version guarantees.
  docs/getting_started/install.md
Labels: pending v0.10.x backport

#2153 Remove deprecated args from `mx.Trainer`.
  setup.cfg
  src/gluonts/mx/trainer/_base.py
  src/gluonts/mx/trainer/learning_rate_scheduler.py
  test/mx/model/deepar/test_deepar_smoke.py
  test/mx/model/deepstate/test_deepstate_smoke.py
  test/mx/model/deepvar/test_deepvar.py
  test/mx/model/gpvar/test_gpvar.py
  test/mx/model/lstnet/test_lstnet.py
  test/mx/test_item_id_info.py
  test/mx/test_mx_serde.py
  test/mx/trainer/test_learning_rate_scheduler.py
  test/paper_examples/test_axiv_paper_examples.py
Labels: BREAKING

#2177 Test: Use spawn method for shell server tests.
  src/gluonts/testutil/shell.py
  test/shell/test_shell.py
Labels: tests

#2179 Docs: fix tutorial after breaking changes in trainer class
  docs/tutorials/forecasting/extended_tutorial.md.template
Labels: pr:docs-build-notebook
