Repository awslabs/gluonts, pull requests merged in 2022-10, with the labels that each got.

#2341 Speed up smoke tests
  test/mx/model/deepar/test_deepar_smoke.py
  test/mx/model/deepstate/test_deepstate_smoke.py
  test/mx/model/seq2seq/test_model.py
Labels: tests

#2339 Add info on how to use 'just'
  docs/community/devsetup.md
Labels: documentation

#2343 Small documentation improvements
  README.md
  docs/community/devsetup.md
  docs/getting_started/background.md
  docs/getting_started/concepts.md
  src/gluonts/dataset/arrow/file.py
  src/gluonts/dataset/artificial/_base.py
  src/gluonts/dataset/multivariate_grouper.py
  src/gluonts/dataset/split.py
  src/gluonts/evaluation/_base.py
  src/gluonts/evaluation/backtest.py
  src/gluonts/model/naive_2/_predictor.py
  src/gluonts/mx/model/lstnet/_estimator.py
  src/gluonts/mx/model/lstnet/_network.py
  src/gluonts/nursery/tsbench/src/tsbench/forecasts/evaluation.py
  src/gluonts/shell/train.py
  src/gluonts/transform/convert.py
  src/gluonts/transform/split.py
Labels: documentation

#2344 Fix numerical bug in `BinnedUniforms`
  src/gluonts/torch/distributions/binned_uniforms.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport

#2356 Remove folders of models that have moved to mx.model
  src/gluonts/model/canonical/__init__.py
  src/gluonts/model/deep_factor/__init__.py
  src/gluonts/model/deepar/__init__.py
  src/gluonts/model/deepstate/__init__.py
  src/gluonts/model/deepvar/__init__.py
  src/gluonts/model/deepvar_hierarchical/__init__.py
  src/gluonts/model/gp_forecaster/__init__.py
  src/gluonts/model/gpvar/__init__.py
  src/gluonts/model/lstnet/__init__.py
  src/gluonts/model/n_beats/__init__.py
  src/gluonts/model/renewal/__init__.py
  src/gluonts/model/san/__init__.py
  src/gluonts/model/seq2seq/__init__.py
  src/gluonts/model/simple_feedforward/__init__.py
  src/gluonts/model/tft/__init__.py
  src/gluonts/model/tpp/__init__.py
  src/gluonts/model/transformer/__init__.py
  src/gluonts/model/wavenet/__init__.py
Labels: BREAKING, models

#2358 Remove model.common.
  src/gluonts/model/common.py
  test/mx/distribution/test_mixture.py
  test/mx/distribution/test_mx_distribution_inference.py
  test/mx/distribution/test_nan_mixture.py
  test/torch/modules/test_torch_distribution_inference.py
Labels: BREAKING

#2359 Udpate `DeepAR` import in README.
  README.md
Labels: documentation

#2361 Remove `dataset.rolling_dataset`.
  examples/run_rolling_forecast_backtest.py
  src/gluonts/dataset/rolling_dataset.py
  test/dataset/test_rolling.py
  test/mx/test_mx_rolling.py
Labels: BREAKING

#2357 Remove `DummyEstimator`.
  src/gluonts/model/estimator.py
  src/gluonts/model/npts/__init__.py
  src/gluonts/model/npts/_estimator.py
  src/gluonts/model/seasonal_naive/__init__.py
  src/gluonts/model/seasonal_naive/_estimator.py
  src/gluonts/model/trivial/_estimator.py
  test/conftest.py
  test/model/npts/test_model.py
  test/model/trivial/test_moving_average.py
  test/shell/test_shell.py
Labels: BREAKING

#2368 Remove strange quoting marks from docstrings
  src/gluonts/mx/model/n_beats/_ensemble.py
  src/gluonts/mx/model/n_beats/_network.py
  src/gluonts/transform/field.py
Labels: documentation

#2373 Consistent use of term "prediction interval"
  docs/getting_started/background.md
  src/gluonts/evaluation/_base.py
  src/gluonts/model/forecast.py
  src/gluonts/model/naive_2/_predictor.py
Labels: documentation

#2360 Add wrapper for `statsforecast` models
  .github/workflows/tests-statsforecast.yaml
  requirements/requirements-extras-statsforecast.txt
  src/gluonts/model/statsforecast.py
  test/model/statsforecast/require-packages.txt
  test/model/statsforecast/test_statsforecast.py
Labels: new feature

#2391 Add `dataset.schema.Schema` + types.
  src/gluonts/dataset/schema/__init__.py
  src/gluonts/dataset/schema/types.py
  test/dataset/schema/test_types.py
Labels: new feature

#2362 Introduce `gluonts.ext`.
  .github/workflows/tests-prophet.yaml
  .github/workflows/tests-statsforecast.yaml
  .github/workflows/tests-xgboost.yaml
  docs/getting_started/models.md
  src/gluonts/evaluation/_base.py
  src/gluonts/ext/README.md
  src/gluonts/ext/__init__.py
  src/gluonts/ext/naive_2/__init__.py
  src/gluonts/ext/naive_2/_predictor.py
  src/gluonts/ext/npts/.typesafe
  src/gluonts/ext/npts/__init__.py
  src/gluonts/ext/npts/_model.py
  src/gluonts/ext/npts/_predictor.py
  src/gluonts/ext/npts/_weighted_sampler.py
  src/gluonts/ext/prophet/.typesafe
  src/gluonts/ext/prophet/__init__.py
  src/gluonts/ext/prophet/_predictor.py
  src/gluonts/ext/r_forecast/R/hierarchical_forecast_methods.R
  src/gluonts/ext/r_forecast/R/univariate_forecast_methods.R
  src/gluonts/ext/r_forecast/__init__.py
  src/gluonts/ext/r_forecast/_hierarchical_predictor.py
  src/gluonts/ext/r_forecast/_predictor.py
  src/gluonts/ext/r_forecast/_univariate_predictor.py
  src/gluonts/ext/rotbaum/README_LSF.ipynb
  src/gluonts/ext/rotbaum/__init__.py
  src/gluonts/ext/rotbaum/_estimator.py
  src/gluonts/ext/rotbaum/_model.py
  src/gluonts/ext/rotbaum/_predictor.py
  src/gluonts/ext/rotbaum/_preprocess.py
  src/gluonts/ext/statsforecast.py
  test/ext/naive_2/r_naive_2_inputs.csv
  test/ext/naive_2/r_naive_2_outputs.csv
  test/ext/naive_2/require-packages.txt
  test/ext/naive_2/test_predictors.py
  test/ext/naive_2/test_r_code_compliance_of_naive_2.py
  test/ext/npts/__init__.py
  test/ext/npts/test_model.py
  test/ext/npts/test_npts.py
  test/ext/prophet/require-packages.txt
  test/ext/prophet/test_prophet.py
  test/ext/r_forecast/test_r_hierarchical_predictor.py
  test/ext/r_forecast/test_r_univariate_predictor.py
  test/ext/rotbaum/__init__.py
  test/ext/rotbaum/require-packages.txt
  test/ext/rotbaum/test_model.py
  test/ext/rotbaum/test_rotbaum_smoke.py
  test/ext/statsforecast/require-packages.txt
  test/ext/statsforecast/test_statsforecast.py
  test/mx/model/deepstate/__init__.py
  test/mx/model/deepvar/__init__.py
  test/mx/model/deepvar_hierarchical/__init__.py
  test/mx/model/gpvar/__init__.py
  test/mx/model/lstnet/__init__.py
Labels: BREAKING

#1784 Add IQN implementation
  src/gluonts/torch/distributions/__init__.py
  src/gluonts/torch/distributions/affine_transformed.py
  src/gluonts/torch/distributions/distribution_output.py
  src/gluonts/torch/distributions/implicit_quantile_network.py
  src/gluonts/torch/model/deep_npts/_network.py
  src/gluonts/torch/modules/loss.py
  test/torch/distribution/test_discrete_distribution.py
  test/torch/model/test_estimators.py
  test/torch/modules/test_torch_distribution_inference.py
Labels: new feature

#2396 Add hierarchical time series reconciliation methods from R/hts: top-down and middle-out
  src/gluonts/ext/r_forecast/R/hierarchical_forecast_methods.R
  src/gluonts/ext/r_forecast/_hierarchical_predictor.py
  test/ext/r_forecast/test_r_hierarchical_predictor.py
Labels: enhancement, models, new feature
