Repository awslabs/gluonts, pull requests merged in 2022-06, with the labels that each got.

#1987 Add HP tuning example with Optuna
  docs/tutorials/hyperparameter_tuning/hp_tuning_with_optuna.md
  docs/tutorials/index.rst
  requirements/requirements-docs.txt
Labels: documentation, other change

#1999 Documentation: fix and speed up tutorials
  docs/tutorials/forecasting/extended_tutorial.md
  docs/tutorials/forecasting/quick_start_tutorial.md
  docs/tutorials/hyperparameter_tuning/hp_tuning_with_optuna.md
  docs/tutorials/mxnet_models/trainer_callbacks.md
Labels: documentation, other change

#2002 add ND for item_metrics
  src/gluonts/evaluation/_base.py
Labels: enhancement

#1997 Remove `freq` argument from `Forecast`.
  src/gluonts/dataset/util.py
  src/gluonts/evaluation/_base.py
  src/gluonts/evaluation/backtest.py
  src/gluonts/evaluation/metrics.py
  src/gluonts/model/forecast.py
  src/gluonts/model/forecast_generator.py
  src/gluonts/model/n_beats/_ensemble.py
  src/gluonts/model/naive_2/_predictor.py
  src/gluonts/model/npts/_model.py
  src/gluonts/model/predictor.py
  src/gluonts/model/prophet/_predictor.py
  src/gluonts/model/r_forecast/_predictor.py
  src/gluonts/model/rotbaum/_predictor.py
  src/gluonts/model/seasonal_naive/_predictor.py
  src/gluonts/model/tpp/forecast.py
  src/gluonts/model/trivial/constant.py
  src/gluonts/model/trivial/identity.py
  src/gluonts/model/trivial/mean.py
  src/gluonts/mx/model/forecast.py
  src/gluonts/nursery/autogluon_tabular/predictor.py
  src/gluonts/torch/model/forecast.py
  test/dataset/test_train_test_data_leakage.py
  test/evaluation/test_evaluator.py
  test/evaluation/test_metrics.py
  test/model/seq2seq/test_quantile_loss.py
  test/model/test_forecast.py
  test/mx/test_distribution_forecast.py
  test/torch/model/test_torch_forecast.py
Labels: BREAKING

#2006 Added support of "long" RTS, making short RTS be "past_feat_dynamic_real"
  src/gluonts/model/rotbaum/_predictor.py
  src/gluonts/model/rotbaum/_preprocess.py
Labels: enhancement

#2011 Remove `dct_reduce`.
  src/gluonts/dataset/util.py
Labels: BREAKING

#2016 Fix torch affine transformed distribution
  src/gluonts/torch/distributions/affine_transformed.py
  test/torch/distribution/test_affine_transformed.py
Labels: bug fix

#2013 Update website template, clean up homepage and tutorials
  Makefile
  docs/Makefile
  docs/_static/gluon_black.png
  docs/_static/google_analytics.js
  docs/community/contribute.rst
  docs/community/index.rst
  docs/conf.py
  docs/figures/Tweets_AMZN_data.png
  docs/figures/Tweets_AMZN_forecast.png
  docs/index.rst
  docs/install.rst
  docs/md2ipynb.py
  docs/tutorials/advanced_topics.zip
  docs/tutorials/advanced_topics/howto_pytorch_lightning.ipynb
  docs/tutorials/advanced_topics/howto_pytorch_lightning.md
  docs/tutorials/advanced_topics/hp_tuning_with_optuna.ipynb
  docs/tutorials/advanced_topics/hp_tuning_with_optuna.md
  docs/tutorials/advanced_topics/trainer_callbacks.ipynb
  docs/tutorials/advanced_topics/trainer_callbacks.md
  docs/tutorials/data_manipulation.zip
  docs/tutorials/data_manipulation/synthetic_data_generation.ipynb
  docs/tutorials/data_manipulation/synthetic_data_generation.md
  docs/tutorials/forecasting.zip
  docs/tutorials/forecasting/extended_tutorial.ipynb
  docs/tutorials/forecasting/quick_start_tutorial.ipynb
  docs/tutorials/index.rst
  requirements/requirements-docs.txt
Labels: documentation

#2020 Remove unnecessary files from `docs` folder, update gitignore
  .gitignore
  docs/tutorials/advanced_topics.zip
  docs/tutorials/advanced_topics/howto_pytorch_lightning.ipynb
  docs/tutorials/advanced_topics/hp_tuning_with_optuna.ipynb
  docs/tutorials/advanced_topics/trainer_callbacks.ipynb
  docs/tutorials/data_manipulation.zip
  docs/tutorials/data_manipulation/synthetic_data_generation.ipynb
  docs/tutorials/forecasting.zip
  docs/tutorials/forecasting/extended_tutorial.ipynb
  docs/tutorials/forecasting/quick_start_tutorial.ipynb
Labels: other change

#2018 Remove multiprocessing dataloader.
  docs/tutorials/forecasting/extended_tutorial.md
  src/gluonts/dataset/common.py
  src/gluonts/dataset/jsonl.py
  src/gluonts/dataset/loader.py
  src/gluonts/dataset/util.py
  src/gluonts/model/canonical/_estimator.py
  src/gluonts/model/deep_factor/_estimator.py
  src/gluonts/model/deepar/_estimator.py
  src/gluonts/model/deepstate/_estimator.py
  src/gluonts/model/deepvar/_estimator.py
  src/gluonts/model/gp_forecaster/_estimator.py
  src/gluonts/model/gpvar/_estimator.py
  src/gluonts/model/lstnet/_estimator.py
  src/gluonts/model/n_beats/_estimator.py
  src/gluonts/model/renewal/_estimator.py
  src/gluonts/model/san/_estimator.py
  src/gluonts/model/seq2seq/_forking_estimator.py
  src/gluonts/model/seq2seq/_seq2seq_estimator.py
  src/gluonts/model/simple_feedforward/_estimator.py
  src/gluonts/model/tft/_estimator.py
  src/gluonts/model/tpp/deeptpp/_estimator.py
  src/gluonts/model/transformer/_estimator.py
  src/gluonts/model/wavenet/_estimator.py
  src/gluonts/mx/model/estimator.py
  src/gluonts/shell/train.py
  test/dataset/test_data_loader.py
  test/dataset/test_dataset_types.py
  test/mx/test_variable_length.py
Labels: BREAKING

#2015 Fix mean in `AffineTransformedDistribution`
  src/gluonts/mx/distribution/transformed_distribution.py
Labels: bug fix, pending v0.9.x backport

#2022 Docs: Put back missing figures
  docs/figures/Tweets_AMZN_data.png
  docs/figures/Tweets_AMZN_forecast.png
Labels: documentation, other change

#2025 Make HP tuning tutorial more accurate
  docs/tutorials/advanced_topics/hp_tuning_with_optuna.md
Labels: enhancement, documentation, other change

#2036 Minor improvements to the hierarchical model
  src/gluonts/model/deepvar_hierarchical/__init__.py
  src/gluonts/model/deepvar_hierarchical/_estimator.py
  src/gluonts/model/deepvar_hierarchical/_network.py
  test/model/deepvar_hierarchical/test_coherency_error.py
  test/model/deepvar_hierarchical/test_reconcile_samples.py
Labels: other change

#1631 Add `TimeLimitCallback` to `mx/trainer` callbacks.
  requirements/requirements.txt
  src/gluonts/mx/trainer/_base.py
  src/gluonts/mx/trainer/callback.py
  src/gluonts/mx/trainer/model_iteration_averaging.py
Labels: BREAKING, new feature

#2035 Simplify lag values computation in torch DeepAR
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/util.py
  test/torch/model/test_deepar_modules.py
  test/torch/model/test_mqf2_modules.py
  test/torch/test_torch_util.py
Labels: enhancement, other change

#2029 Add support for nan values in Rotbaum
  src/gluonts/model/rotbaum/_predictor.py
  src/gluonts/model/rotbaum/_preprocess.py
Labels: enhancement, new feature

#2047 Make `Quantile` derive from `pydantic.BaseModel`.
  src/gluonts/model/forecast.py
Labels: bug fix

#2057 Add optional parameter `time_axis` to `forecast_start`.
  src/gluonts/dataset/util.py
Labels: enhancement

#2051 Add tutorial on `DataFramesDataset`
  docs/index.rst
  docs/tutorials/data_manipulation/dataframesdataset.md
Labels: documentation

#2060 Add support for `pd.Series`
  src/gluonts/dataset/dataframe.py
  test/dataset/test_dataframe.py
Labels: new feature

#2070 Add `jsonl.encode_json`, remove `serialize_data_entry`.
  requirements/requirements-extras-shell.txt
  requirements/requirements-test.txt
  src/gluonts/dataset/common.py
  src/gluonts/dataset/jsonl.py
  src/gluonts/dataset/repository/_artificial.py
  src/gluonts/shell/serve/app.py
  src/gluonts/shell/serve/util.py
  src/gluonts/testutil/shell.py
  test/dataset/test_dataset_types.py
  test/shell/test_shell.py
Labels: BREAKING

#2053 Add `dataset_writer` to `get_dataset`.
  src/gluonts/dataset/artificial/generate_synthetic.py
  src/gluonts/dataset/common.py
  src/gluonts/dataset/repository/_artificial.py
  src/gluonts/dataset/repository/_gp_copula_2019.py
  src/gluonts/dataset/repository/_lstnet.py
  src/gluonts/dataset/repository/_m3.py
  src/gluonts/dataset/repository/_m4.py
  src/gluonts/dataset/repository/_m5.py
  src/gluonts/dataset/repository/_tsf_datasets.py
  src/gluonts/dataset/repository/_uber_tlc.py
  src/gluonts/dataset/repository/_util.py
  src/gluonts/dataset/repository/datasets.py
Labels: BREAKING

#2082 Docs: Fixup of #2080.
  .github/workflows/docs.yml
  Justfile
  Makefile
  docs/md2ipynb.py
Labels: pr:docs-build-notebook

#2094 Fix index checks in `PandasDataset`
  src/gluonts/dataset/pandas.py
  test/dataset/test_pandas.py
Labels: pending v0.10.x backport

#2092 Fix: DistributionLoss not encodable.
  src/gluonts/torch/modules/loss.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport

#2108 Fixup trainer in case of non-finite loss.
  src/gluonts/mx/trainer/_base.py
Labels: pending v0.9.x backport, pending v0.10.x backport

#2107 Fix: Use timestamps for forecast plotting.
  src/gluonts/model/forecast.py
Labels: pending v0.10.x backport

#2104 Add more use-cases for `PandasDataset`
  docs/tutorials/data_manipulation/pandasdataframes.md.input
Labels: enhancement, documentation, pending v0.10.x backport
