Repository awslabs/gluonts, pull requests merged in 2022-08, with the labels that each got.

#2182 Fix Prophet wrapper to work with `Timestamp` instead of `Period`
  .github/workflows/tests-prophet.yaml
  src/gluonts/model/prophet/_predictor.py
  test/model/prophet/test_prophet.py
Labels: pending v0.10.x backport

#2183 Fix dtype for "item_id" column in metrics dataframe
  src/gluonts/evaluation/_base.py
Labels: pending v0.9.x backport, pending v0.10.x backport

#2157 Add tutorial with data splitting examples
  docs/tutorials/advanced_topics/hp_tuning_with_optuna.md.template
  docs/tutorials/data_manipulation/dataset_splitting_example.md.template
  src/gluonts/dataset/split/splitter.py
Labels: pr:docs-build-notebook

#2186 Fix: ensure last cell of tutorials runs
  docs/md2ipynb.py
  docs/tutorials/advanced_topics/trainer_callbacks.md.template
Labels: pending v0.10.x backport, pr:docs-build-notebook

#2192 Fix `item_id` values in `ConstantValuePredictor`
  src/gluonts/model/trivial/constant.py
Labels: bug fix

#2197 Fix: Make `Patience` compatible with `pydantic.dataclass`.
  src/gluonts/mx/trainer/learning_rate_scheduler.py
Labels: bug fix, pending v0.10.x backport

#2196 Fix dataset writer tool.
  src/gluonts/dataset/arrow/__main__.py
  src/gluonts/dataset/arrow/file.py
Labels: bug fix, pending v0.10.x backport

#2199 Reduce sdist size.
  MANIFEST.in
Labels: BREAKING

#2203 Remove core.ty.
  src/gluonts/core/serde/_base.py
  src/gluonts/core/ty.py
  test/core/test_ty.py
Labels: BREAKING

#2204 Fix `aggregate_valid` function to ignore non-numeric columns
  src/gluonts/evaluation/_base.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport

#2187 Fix `SymbolBlock` serde issue
  src/gluonts/mx/util.py
  test/mx/model/simple_feedforward/test_serde.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport

#2209 Update Available models table with the hierarchical model
  docs/getting_started/models.md
Labels: documentation, pending v0.10.x backport

#2216 Fix `r_forecast` wrapper to shift start date when truncating time series
  src/gluonts/model/r_forecast/_predictor.py
  test/model/r_forecast/test_r_predictor.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport

#2225 Fix bug in `to_quantile_forecast`
  src/gluonts/model/forecast.py
Labels: pending v0.9.x backport, pending v0.10.x backport

#1835 Add Deep NPTS model
  src/gluonts/torch/distributions/discrete_distribution.py
  src/gluonts/torch/model/deep_npts/.typesafe
  src/gluonts/torch/model/deep_npts/__init__.py
  src/gluonts/torch/model/deep_npts/_estimator.py
  src/gluonts/torch/model/deep_npts/_network.py
  src/gluonts/torch/model/deep_npts/scaling.py
  test/torch/distribution/test_discrete_distribution.py
  test/torch/model/test_deep_npts.py
Labels: new feature

#2223 Update `gluonts.dataset.split` code, test, docs
  docs/tutorials/advanced_topics/hp_tuning_with_optuna.md.template
  docs/tutorials/data_manipulation/dataset_splitting_example.md.template
  src/gluonts/dataset/split.py
  src/gluonts/dataset/split/__init__.py
  test/dataset/test_split.py
Labels: BREAKING, pr:docs-build-notebook

#2228 Fix `gluonts.mx.trainer.Trainer` in case of empty data loader
  src/gluonts/mx/trainer/_base.py
  test/mx/test_no_batches.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport

#2217 Speedup data reader
  src/gluonts/dataset/arrow/dec.py
  test/dataset/test_arrow.py
Labels: enhancement, pending v0.10.x backport

#2233 Update minimal version for nbconvert.
  requirements/requirements-docs.txt
Labels: pr:docs-build-notebook

#2226 Allow DeepVAR model to use (global) dynamic features
  src/gluonts/dataset/artificial/_base.py
  src/gluonts/dataset/multivariate_grouper.py
  src/gluonts/dataset/stat.py
  src/gluonts/mx/model/deepvar/_estimator.py
  test/mx/model/deepvar/test_deepvar.py
Labels: new feature

#2238 Fix feed-forward models when features are provided
  src/gluonts/dataset/field_names.py
  src/gluonts/mx/model/simple_feedforward/_estimator.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/transform/field.py
  test/mx/test_mx_item_id_info.py
  test/torch/test_torch_item_id_info.py
Labels: bug fix

#2253 Hierarchical: Allow use of external dynamic features and add a section in the tutorial
  docs/tutorials/forecasting/hierarchical_model_tutorial.md.template
  src/gluonts/dataset/hierarchical.py
  src/gluonts/mx/model/deepvar_hierarchical/_estimator.py
  test/mx/model/deepvar_hierarchical/test_train_prediction_with_hts.py
Labels: documentation, new feature, pr:docs-build-notebook

#2261 Improve len() for ParquetFile.
  src/gluonts/dataset/arrow/file.py
Labels: bug fix, pending v0.10.x backport

#2262 Max idle transform fix
  src/gluonts/mx/model/canonical/_estimator.py
  src/gluonts/mx/model/deep_factor/_estimator.py
  src/gluonts/mx/model/deepar/_estimator.py
  src/gluonts/mx/model/deepstate/_estimator.py
  src/gluonts/mx/model/deepvar/_estimator.py
  src/gluonts/mx/model/estimator.py
  src/gluonts/mx/model/gp_forecaster/_estimator.py
  src/gluonts/mx/model/gpvar/_estimator.py
  src/gluonts/mx/model/lstnet/_estimator.py
  src/gluonts/mx/model/n_beats/_estimator.py
  src/gluonts/mx/model/renewal/_estimator.py
  src/gluonts/mx/model/san/_estimator.py
  src/gluonts/mx/model/seq2seq/_forking_estimator.py
  src/gluonts/mx/model/seq2seq/_seq2seq_estimator.py
  src/gluonts/mx/model/simple_feedforward/_estimator.py
  src/gluonts/mx/model/tft/_estimator.py
  src/gluonts/mx/model/tpp/deeptpp/_estimator.py
  src/gluonts/mx/model/transformer/_estimator.py
  src/gluonts/mx/model/wavenet/_estimator.py
  src/gluonts/transform/_base.py
Labels: pending v0.9.x backport, pending v0.10.x backport, performance improvement

#2259 Optimize `TimeSeriesSlice` performance
  src/gluonts/dataset/split.py
  test/dataset/test_split.py
Labels: pr:docs-build-notebook, performance improvement

#2263 Fix ignore hidden files when generating datasets
  src/gluonts/dataset/repository/_gp_copula_2019.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport
