Repository awslabs/gluonts, pull requests merged in 2022-03, with the labels that each got.

#1916 Fix AddTimeFeatures transformation for multiples of base frequencies
  src/gluonts/transform/feature.py
  test/transform/test_add_time_features.py
  test/transform/test_transform.py
Labels: bug fix, pending v0.9.x backport

#1919 Update docs requirements
  requirements/requirements-docs.txt
Labels: dev setup

#1917 Breaking: Fix return types of features
  src/gluonts/time_feature/_base.py
  test/time_feature/test_features.py
Labels: BREAKING, bug fix

#1920 Fix: use broadcast_lesser in place of comparisons in ISQF
  src/gluonts/mx/distribution/isqf.py
Labels: bug fix, pending v0.9.x backport

#1925 DeepAR PyTorch: make samplers configurable
  src/gluonts/torch/model/deepar/estimator.py
Labels: enhancement

#1924 Porting SimpleFeedForwardEstimator to PyTorch
  README.md
  src/gluonts/torch/model/simple_feedforward/.typesafe
  src/gluonts/torch/model/simple_feedforward/__init__.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/torch/model/simple_feedforward/lightning_module.py
  src/gluonts/torch/model/simple_feedforward/module.py
  test/torch/model/test_estimators.py
  test/torch/model/test_simple_torch_model.py
Labels: new feature

#1927 Fix: remove unused freq from SimpleFeedForward
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/torch/model/simple_feedforward/module.py
Labels: other change

#1929 Add multiprocessing to validation data loader
  src/gluonts/dataset/loader.py
  src/gluonts/model/seq2seq/_forking_estimator.py
  src/gluonts/mx/model/estimator.py
  test/dataset/test_data_loader.py
Labels: enhancement

#1931 Fix dummy estimator
  src/gluonts/model/estimator.py
Labels: bug fix, pending v0.9.x backport
