Repository awslabs/gluonts, pull requests merged in 2022-09, with the labels that each got.

#1685 R: Add Python wrapper for calling R's hierarchical methods
  src/gluonts/model/r_forecast/R/hierarchical_forecast_methods.R
  src/gluonts/model/r_forecast/R/univariate_forecast_methods.R
  src/gluonts/model/r_forecast/__init__.py
  src/gluonts/model/r_forecast/_hierarchical_predictor.py
  src/gluonts/model/r_forecast/_predictor.py
  src/gluonts/model/r_forecast/_univariate_predictor.py
  test/conftest.py
  test/model/r_forecast/test_r_hierarchical_predictor.py
  test/model/r_forecast/test_r_univariate_predictor.py
  test/mx/model/deepvar_hierarchical/generate_hierarchical_dataset.py
  test/mx/model/deepvar_hierarchical/test_deepvar_hierarchical.py
Labels: BREAKING, new feature

#2265 Hierarchical: Add a test for to_dataset method
  test/dataset/test_hierarchical.py
Labels: tests

#2266 Fix: set max idle transforms in PyTorch estimators
  src/gluonts/torch/model/estimator.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport

#2269 Fix `QuantileForecast.plot()` to use `DateTimeIndex`
  requirements/requirements-test.txt
  src/gluonts/model/forecast.py
  test/model/test_forecast.py
Labels: bug fix, pending v0.10.x backport

#2271 Fix mypy and black commands in pre-commit githook
  .devtools/githooks/pre-commit
Labels: dev setup

#2270 Docs: update contribution guidelines and dev setup
  CONTRIBUTING.md
  docs/community/contribute.rst
  docs/community/devsetup.md
Labels: documentation, pending v0.10.x backport

#2274 Update project_urls.
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/test_release_unix_nightly.yml
  .github/workflows/test_release_win32_nightly.yml
  CONTRIBUTING.md
  README.md
  docs/getting_started/install.md
  docs/getting_started/models.md
  examples/GluonTS_SageMaker_SDK_Tutorial.ipynb
  examples/dockerfiles/README.md
  setup.py
  src/gluonts/dataset/repository/_gp_copula_2019.py
  src/gluonts/mx/batchify.py
  src/gluonts/nursery/QRX-Wrapped-M5-Accuracy-Solution/0. README.md
  src/gluonts/nursery/sagemaker_sdk/estimator.py
  src/gluonts/nursery/tsbench/README.md
  src/gluonts/nursery/tsbench/pyproject.toml
  test/mx/test_mx_rolling.py
Labels: pending v0.9.x backport, pending v0.10.x backport

#2277 Fix serde dataclass eventual.
  src/gluonts/core/serde/_dataclass.py
  test/core/test_serde_dataclass.py
Labels: pending v0.10.x backport

#2278 Remove gluonts_forecasters entrypoint mechanic.
  setup.py
  src/gluonts/shell/util.py
  test/test_forecaster_entrypoints.py
Labels: BREAKING

#2289 Add learning rate and weight decay arguments to PyTorch estimators
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/mqf2/estimator.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
Labels: enhancement

#2287 Added LR scheduler to DeepAR Pytorch
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/deepar/lightning_module.py
Labels: enhancement

#2297 Fix README quick examples
  README.md
Labels: documentation, pending v0.10.x backport

#2300 Fix text in Quick Start Tutorial
  docs/tutorials/forecasting/quick_start_tutorial.md.template
Labels: documentation, pending v0.10.x backport

#2307 Add input size and type information to DeepARModel
  src/gluonts/torch/model/deepar/lightning_module.py
  src/gluonts/torch/model/deepar/module.py
Labels: enhancement

#2314 Fix `gluonts.dataset.split` for multivariate case
  src/gluonts/dataset/rolling_dataset.py
  src/gluonts/dataset/split.py
  test/dataset/test_split.py
Labels: bug fix

#2304 Add dataset.schema.translate.
  src/gluonts/dataset/common.py
  src/gluonts/dataset/schema/__init__.py
  src/gluonts/dataset/schema/translate.py
  test/dataset/schema/test_translate.py
Labels: new feature

#2315 Improve `TestData` class in `gluonts.dataset.split`
  src/gluonts/dataset/split.py
Labels: enhancement

#2309 Simplify `make_evaluation_predictions`
  src/gluonts/dataset/util.py
  src/gluonts/evaluation/backtest.py
  test/evaluation/test_backtest_tools.py
Labels: enhancement, pr:docs-build-notebook

#2321 Fix MQCNN for `kernel_size=1`
  src/gluonts/mx/block/cnn.py
  src/gluonts/mx/model/seq2seq/_mq_dnn_estimator.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport
