Repository awslabs/gluonts, pull requests merged in 2022-11, with the labels that each got.

#2408 Fix rotbaum random seed and `num_samples` argument.
  src/gluonts/ext/rotbaum/_preprocess.py
Labels: bug fix

#2406 Add hierarchical time series reconciliation method from R/hts: MinT
  src/gluonts/ext/r_forecast/R/hierarchical_forecast_methods.R
  src/gluonts/ext/r_forecast/_hierarchical_predictor.py
  test/conftest.py
  test/ext/r_forecast/test_r_hierarchical_predictor.py
  test/mx/model/deepvar_hierarchical/test_deepvar_hierarchical.py
Labels: enhancement, models, new feature

#2415 Hierarchical: Make sure the input S matrix is of right dtype
  src/gluonts/mx/model/deepvar_hierarchical/_estimator.py
Labels: bug fix, pending v0.11.x backport

#2426 `itertools.select`.
  src/gluonts/itertools.py
  test/test_itertools.py
Labels: new feature

#2352 Add `copy_dim` to `QuantileForecast`, change `dim` method for multivariate data
  src/gluonts/model/forecast.py
  test/model/test_forecast.py
Labels: enhancement, BREAKING

#2435 Speed up `PandasDataset` for long dataframes
  src/gluonts/dataset/pandas.py
  src/gluonts/itertools.py
  test/dataset/test_pandas.py
Labels: bug fix, pending v0.11.x backport

#2442 Fix frequency inference in `PandasDataset`
  src/gluonts/dataset/pandas.py
Labels: bug fix, pr:docs-build-notebook, pending v0.11.x backport

#2439 Add cdf and icdf methods for StudentT distribution
  src/gluonts/torch/distributions/__init__.py
  src/gluonts/torch/distributions/distribution_output.py
  src/gluonts/torch/distributions/studentT.py
  test/torch/distribution/test_studentt.py
Labels: enhancement, new feature

#2433 Better DeepAR lags for business day frequency time series.
  src/gluonts/time_feature/lag.py
Labels: enhancement, models

#2447 Update workflow actions to latest versions
  .github/workflows/docs.yml
  .github/workflows/flake8.yml
  .github/workflows/mxnet_nightly.yml
  .github/workflows/pypi.yml
  .github/workflows/style_type_checks.yml
  .github/workflows/test_release_unix_nightly.yml
  .github/workflows/test_release_win32_nightly.yml
  .github/workflows/tests-nursery.yml
  .github/workflows/tests-prophet.yaml
  .github/workflows/tests-statsforecast.yaml
  .github/workflows/tests-torch.yml
  .github/workflows/tests-xgboost.yaml
  .github/workflows/tests.yml
Labels: other change

#2446 Fix plotting date index bug in anomaly detection example
  examples/anomaly_detection.py
Labels: bug fix

#2453 Add test cases for `PandasDataset`, fix missing assertion
  src/gluonts/dataset/pandas.py
  src/gluonts/testutil/equality.py
  test/dataset/test_pandas.py
Labels: tests, bug fix, pending v0.11.x backport

#2450 Introduce `ev` module
  .github/workflows/tests-torch.yml
  src/gluonts/ev/__init__.py
  src/gluonts/ev/aggregations.py
  src/gluonts/ev/evaluator.py
  src/gluonts/ev/metrics.py
  src/gluonts/ev/stats.py
  src/gluonts/ev/ts_stats.py
  test/ev/test_aggregations.py
  test/ev/test_metrics_compared_to_previous_approach.py
  test/ev/test_stats.py
Labels: new feature

#2441 Speed up `PandasDataset` further
  src/gluonts/dataset/pandas.py
Labels: enhancement, pending v0.11.x backport

#2463 Add `itertools.inverse.`
  src/gluonts/itertools.py
Labels: new feature

#2472 Set default `forecast_type` of ND metric to median
  src/gluonts/ev/metrics.py
Labels: bug fix
