Repository awslabs/gluonts, pull requests merged in 2022-12, with the labels that each got.

#2478 Fix: use right context in DeepVARHierarchicalEstimator
  src/gluonts/mx/model/deepvar_hierarchical/_estimator.py
Labels: bug fix, pending v0.11.x backport

#2482 Remove serde dump_code/load_code.
  src/gluonts/core/component.py
  src/gluonts/core/serde/__init__.py
  src/gluonts/core/serde/_base.py
  src/gluonts/core/serde/_repr.py
  src/gluonts/evaluation/backtest.py
  src/gluonts/nursery/tsbench/src/tsbench/evaluations/training/logging.py
  src/gluonts/shell/train.py
  test/conftest.py
  test/core/test_component.py
  test/core/test_serde.py
  test/dataset/artificial/test_recipe.py
  test/ext/npts/test_model.py
  test/ext/rotbaum/test_model.py
  test/model/test_backtest.py
  test/mx/distribution/test_distribution_sampling.py
  test/mx/model/canonical/test_model.py
  test/mx/model/deep_factor/test_model.py
  test/mx/model/deepar/test_model.py
  test/mx/model/deepstate/test_model.py
  test/mx/model/gp_forecaster/test_model.py
  test/mx/model/n_beats/test_model.py
  test/mx/model/renewal/test_model.py
  test/mx/model/seq2seq/test_model.py
  test/mx/model/simple_feedforward/test_model.py
  test/mx/model/tft/test_model.py
  test/mx/model/transformer/test_model.py
  test/mx/model/wavenet/test_model.py
  test/mx/test_mx_serde.py
  test/transform/test_transform.py
Labels: BREAKING

#2488 Fix use of dump_code in tutorial.
  docs/tutorials/data_manipulation/synthetic_data_generation.md.template
Labels: pr:docs-build-notebook

#2490 Add requirement files to MANIFEST.in
  MANIFEST.in
Labels: pending v0.11.x backport

#2495 Add smoke tests for torch models
  src/gluonts/torch/model/mqf2/module.py
  src/gluonts/torch/model/simple_feedforward/module.py
  test/torch/model/test_modules.py
Labels: enhancement, tests

#2497 Fix: sort dataset keys in error message when importing non-existing dataset
  src/gluonts/dataset/repository/datasets.py
Labels: enhancement

#2500 Fix `DateSplitter` for multiples of base frequencies
  src/gluonts/dataset/split.py
  test/dataset/test_split.py
Labels: bug fix, pending v0.11.x backport

#2501 Fix docstrings according to docformatter
  src/gluonts/core/serde/_dataclass.py
  src/gluonts/core/settings.py
  src/gluonts/dataset/__init__.py
  src/gluonts/dataset/arrow/file.py
  src/gluonts/dataset/artificial/_base.py
  src/gluonts/dataset/hierarchical.py
  src/gluonts/dataset/pandas.py
  src/gluonts/dataset/split.py
  src/gluonts/itertools.py
Labels: documentation, pending v0.11.x backport

#2508 Docs: Fix install instructions.
  docs/getting_started/install.md
Labels: pending v0.11.x backport

#2504 Add examples to docstring for `periods_between`
  src/gluonts/dataset/split.py
Labels: pending v0.11.x backport

#2512 Fix `serde.dataclass` inheritance handling.
  src/gluonts/core/serde/_dataclass.py
  test/core/test_serde_dataclass.py
Labels: bug fix, pending v0.11.x backport

#2513 Fix `QuantileForecast.quantile` in case only mean is stored
  src/gluonts/model/forecast.py
  test/model/test_forecast.py
Labels: bug fix, pending v0.11.x backport

#2514 Remove mypy plugin for dataclass.
  setup.cfg
  src/gluonts/core/serde/__init__.py
  src/gluonts/core/serde/_dataclass.py
  src/gluonts/meta/_mypy_plugin.py
Labels: pending v0.11.x backport

#2412 Add Empirical Risk Minimzation (ERM) hierarchical forecasting method
  src/gluonts/ext/r_forecast/R/hierarchical_forecast_methods.R
  src/gluonts/ext/r_forecast/_hierarchical_predictor.py
  test/ext/r_forecast/test_r_hierarchical_predictor.py
Labels: enhancement, models, new feature
