Repository awslabs/gluonts, pull requests merged in 2023-03, with the labels that each got.

#2701 Docs: minor spelling fix
  docs/getting_started/concepts.md
  docs/getting_started/install.md
Labels: documentation, pending v0.12.x backport

#2700 Fix zebras period time features.
  src/gluonts/zebras/_period.py
  test/zebras/test_period.py
Labels: bug fix

#2704 `torch.SimpleFeedForward`: Rename `context` to `past_target`.
  src/gluonts/torch/model/simple_feedforward/module.py
Labels: BREAKING

#2709 update hierarchicalforecast for new release
  requirements/requirements-extras-hierarchicalforecast.txt
  src/gluonts/ext/hierarchicalforecast.py
Labels: bug fix

#2710 Fix Pandas 2.0 compatibility issues
  src/gluonts/core/serde/pd.py
  test/dataset/artificial/test_recipe.py
  test/dataset/test_stat.py
  test/mx/block/__init__.py
  test/torch/__init__.py
Labels: enhancement, dependency

#2715 hierarchical forecast wrapper - improve comprehension list style
  src/gluonts/ext/hierarchicalforecast.py
Labels: enhancement

#2618 Fix off-by-one in torch DeepAR
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/util.py
  test/torch/model/test_deepar_modules.py
Labels: BREAKING, bug fix, torch

#2724 Allow PyTorch 2.0
  .github/workflows/tests-torch.yml
  requirements/requirements-pytorch.txt
Labels: enhancement, dependency, pending v0.12.x backport

#2726 Improve check for validation loop in lightning modules
  src/gluonts/torch/model/deepar/lightning_module.py
  src/gluonts/torch/model/lightning_util.py
  src/gluonts/torch/model/tft/lightning_module.py
Labels: enhancement

#2729 Fix _version location for sdist.
  MANIFEST.in
  src/gluonts/meta/_version.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2731 Add warning for "object" features in PandasDataset
  src/gluonts/dataset/pandas.py
Labels: enhancement, pending v0.12.x backport

#2733 Fix validation loop check for Lightning modules
  src/gluonts/torch/model/lightning_util.py
  test/torch/model/test_estimators.py
Labels: bug fix, pending v0.12.x backport

#2737 Remove usage of glide in tsf-reader.
  src/gluonts/dataset/repository/_tsf_reader.py
Labels: pending v0.12.x backport

#2740 Update Available Models
  docs/getting_started/models.md
Labels: documentation, pending v0.12.x backport

#2738 Fix: use non-strict inequality in definition of coverage
  src/gluonts/ev/stats.py
  src/gluonts/evaluation/metrics.py
  test/ev/test_stats.py
  test/evaluation/test_metrics.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2744 Fix MXNet NOPScaler
  src/gluonts/mx/block/scaler.py
Labels: bug fix, pending v0.12.x backport

#2756 Add itertools.PickleCache.
  src/gluonts/itertools.py
  test/test_itertools.py
Labels: new feature
