Repository awslabs/gluonts, pull requests merged in 2023-08, with the labels that each got.

#2953 [Docs] fix link to NPTS implementation
  docs/getting_started/models.md
Labels: documentation, pending v0.13.x backport

#2951 Fix: prevent accumulation of `SelectFields` in `PyTorchPredictor`
  src/gluonts/torch/model/predictor.py
Labels: bug fix, pending v0.13.x backport

#2956 Add fit to gaussian
  src/gluonts/mx/distribution/gaussian.py
Labels: enhancement

#2958 Turn `type` comparison into `isinstance`
  src/gluonts/mx/model/seq2seq/_mq_dnn_estimator.py
Labels: enhancement

#2957 Nonnegative predictions for deepar mxnet
  src/gluonts/mx/model/deepar/_estimator.py
  src/gluonts/mx/model/deepar/_network.py
  test/mx/model/deepar/test_nonnegative_pred_samples.py
Labels: enhancement

#2959 Nonnegative predictions for deepar-pytorch
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/deepar/module.py
  test/torch/model/test_deepar_nonnegative_pred_samples.py
Labels: enhancement

#2962 Add laplace distribution to torch distributions
  src/gluonts/torch/distributions/__init__.py
  src/gluonts/torch/distributions/distribution_output.py
Labels: enhancement

#2966 Fix Cython version in XGBoost tests
  .github/workflows/tests-xgboost.yaml
Labels: CI

#2967 Clean up RepresentablePredictor
  src/gluonts/model/predictor.py
Labels: enhancement

#2965 Simplify PyTorchPredictor serde
  src/gluonts/model/predictor.py
  src/gluonts/torch/model/d_linear/estimator.py
  src/gluonts/torch/model/deep_npts/_estimator.py
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/lag_tst/estimator.py
  src/gluonts/torch/model/patch_tst/estimator.py
  src/gluonts/torch/model/predictor.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/torch/model/tft/estimator.py
  src/gluonts/torch/model/wavenet/estimator.py
  test/torch/model/test_estimators.py
  test/torch/model/test_torch_predictor.py
Labels: enhancement, BREAKING

#2973 Fix: use `isinstance` instead of type comparison
  src/gluonts/core/serde/_base.py
Labels: bug fix

#2974 Move LookupValues from Wavenet to gluonts.torch.modules
  src/gluonts/torch/model/wavenet/module.py
  src/gluonts/torch/modules/lookup_table.py
Labels: enhancement

#2975 Move QuantizeScaled from Wavenet to gluonts.transform, rename to QuantizeMeanScaled
  src/gluonts/torch/model/wavenet/estimator.py
  src/gluonts/transform/__init__.py
  src/gluonts/transform/convert.py
Labels: enhancement, BREAKING

#2976 Fix ArrowDecoder.decode to return instead of yield
  src/gluonts/dataset/arrow/dec.py
  test/dataset/test_arrow.py
Labels: bug fix

#2977 Unpin pyarrow version
  requirements/requirements-arrow.txt
Labels: enhancement, pending v0.13.x backport

#2980 fixed an error in the readme
  src/gluonts/ext/rotbaum/README_LSF.ipynb
Labels: documentation

#2983 [R] Bug fix for running R methods via ParallelizedPredictor
  src/gluonts/ext/r_forecast/_univariate_predictor.py
Labels: bug fix, pr:test-r, pending v0.13.x backport

#2879 Breaking: change num_output with quantiles in TFT (mxnet)
  src/gluonts/mx/model/tft/_estimator.py
  src/gluonts/mx/model/tft/_network.py
Labels: enhancement, BREAKING, mxnet

#2843 Raise warning in `QuantileForecast.mean` when mean is not there
  src/gluonts/model/forecast.py
Labels: enhancement, pending v0.13.x backport

#2984 Update Predictor checkpoint structure
  src/gluonts/model/predictor.py
Labels: enhancement

#2985 Change torch state_dict file name to prediction-net-state.pt
  src/gluonts/torch/model/predictor.py
Labels: BREAKING, torch

#2989 Fix return type in `gluonts.evaluation.metrics`
  src/gluonts/evaluation/metrics.py
Labels: other change
