Repository awslabs/gluonts, pull requests merged in 2023-04, with the labels that each got.

#2777 Fix dataset file discovery.
  src/gluonts/dataset/common.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2778 Fix pandas removed deprecations in tests
  requirements/requirements-test.txt
  test/conftest.py
  test/evaluation/test_evaluator.py
  test/mx/model/deepvar_hierarchical/generate_hierarchical_dataset.py
  test/mx/trainer/test_model_iteration_averaging.py
  test/torch/model/test_torch_forecast.py
  test/zebras/test_period.py
Labels: tests, pending v0.12.x backport

#2779 Fix: Loading of nested paths in FileDataset.
  src/gluonts/dataset/common.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2786 Test: Set caplog level for shell tests.
  test/shell/test_shell.py
Labels: pending v0.11.x backport, pending v0.12.x backport

#2796 Reduce depth of `get_dataset` import
  src/gluonts/dataset/repository/__init__.py
Labels: enhancement

#2798 Remove dataset.Schema.
  src/gluonts/dataset/schema/__init__.py
  src/gluonts/dataset/schema/types.py
  test/dataset/schema/test_types.py
Labels: BREAKING

#2673 Add interface to `gluonts.ev`
  src/gluonts/model/__init__.py
  src/gluonts/model/evaluation.py
  test/model/test_evaluation.py
Labels: new feature

#2800 Remove `.to_timestamp()` to fix interval plotting
  src/gluonts/model/forecast.py
Labels: bug fix

#2806 Fix: remove multiprocessing from `TSFReader`
  src/gluonts/dataset/repository/_tsf_reader.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2807 Zebras: Add `from_pandas` classmethods to `TimeFrame` and `Periods`.
  src/gluonts/zebras/__init__.py
  src/gluonts/zebras/_period.py
  src/gluonts/zebras/_time_frame.py
  test/zebras/test_from_pandas.py
Labels: enhancement

#2814 Add test workflow for R based models
  .github/workflows/tests-r.yml
Labels: pr:test-r

#2815 Add `SizedIterableSlice`, an `IterableSlice` that supports `len()`
  src/gluonts/itertools.py
  test/test_itertools.py
Labels: enhancement

#2819 Add tests for hierarchical model to R workflow
  .github/workflows/tests-r.yml
Labels: pr:test-r

#2825 Refactor base metrics computation in Evaluator class
  src/gluonts/evaluation/_base.py
Labels: enhancement
