Repository awslabs/gluonts, pull requests merged in 2023-01, with the labels that each got.

#2515 Update `statsforecast` model wrappers
  src/gluonts/ext/statsforecast.py
  test/ext/statsforecast/test_statsforecast.py
Labels: enhancement, BREAKING, new feature

#2526 Fix `aggregate_valid` for non-numerical columns
  src/gluonts/evaluation/_base.py
  test/evaluation/test_evaluator.py
Labels: bug fix, pending v0.11.x backport

#2534 Move `SelfAttentionEstimator` to `gluonts.nursery`
  docs/getting_started/models.md
  src/gluonts/mx/__init__.py
  src/gluonts/nursery/san/__init__.py
  src/gluonts/nursery/san/_estimator.py
  src/gluonts/nursery/san/_layers.py
  src/gluonts/nursery/san/_network.py
Labels: BREAKING

#2537 nan values and explainability support for rotbaum
  src/gluonts/ext/rotbaum/_predictor.py
  src/gluonts/ext/rotbaum/_preprocess.py
  src/gluonts/ext/rotbaum/_types.py
Labels: new feature, bug fix

#2538 Improve README example
  README.md
Labels: documentation

#2544 Simplify forecast.Quantile.
  src/gluonts/evaluation/_base.py
  src/gluonts/model/forecast.py
  test/ev/test_metrics_compared_to_previous_approach.py
Labels: BREAKING

#2545 Enable setting a custom imputation method in deepar pytorch
  src/gluonts/torch/model/deepar/estimator.py
Labels: enhancement

#2547 Move shell related forecast classes to shell.
  src/gluonts/model/forecast.py
  src/gluonts/mx/model/tpp/forecast.py
  src/gluonts/shell/env.py
  src/gluonts/shell/serve/app.py
Labels: BREAKING

#2553 Add default_scale to MeanScaler and enable the option in DeepAR-PyTorch
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/modules/scaler.py
Labels: enhancement

#2558 Compact PandasDataset string representation
  src/gluonts/dataset/pandas.py
Labels: enhancement, pending v0.11.x backport

#2556 Add default args and assertions to DeepAR pytorch module, assertions
  src/gluonts/torch/model/deepar/module.py
Labels: enhancement

#2554 Fix: add missing params in rotbaum
  src/gluonts/ext/rotbaum/_preprocess.py
Labels: bug fix

#2561 Add statsforecasts models
  src/gluonts/ext/statsforecast.py
  test/ext/statsforecast/test_statsforecast.py
Labels: models, new feature

#2536 Add TemporalFusionTransformer implementation in PyTorch
  docs/bibliography.rst
  src/gluonts/dataset/field_names.py
  src/gluonts/model/forecast_generator.py
  src/gluonts/mx/model/tft/_estimator.py
  src/gluonts/mx/model/tft/_transform.py
  src/gluonts/torch/model/tft/__init__.py
  src/gluonts/torch/model/tft/estimator.py
  src/gluonts/torch/model/tft/layers.py
  src/gluonts/torch/model/tft/lightning_module.py
  src/gluonts/torch/model/tft/module.py
  src/gluonts/torch/modules/quantile_output.py
  src/gluonts/torch/modules/scaler.py
  src/gluonts/transform/split.py
  test/torch/model/test_estimators.py
  test/torch/model/test_modules.py
  test/torch/model/test_tft.py
Labels: models, new feature

#2568 Add NaN validation to Evaluator
  src/gluonts/evaluation/_base.py
  test/evaluation/test_evaluator.py
Labels: bug fix, pending v0.11.x backport

#2569 Add missing value imputation to Seasonal Naive
  src/gluonts/model/seasonal_naive/_predictor.py
  test/model/seasonal_naive/test_seasonal_naive.py
Labels: enhancement

#2571 Fix `r_forecast` methods to work with rpy2 v3+
  requirements/requirements-extras-r.txt
  src/gluonts/ext/r_forecast/_predictor.py
  test/ext/r_forecast/test_r_hierarchical_predictor.py
  test/ext/r_forecast/test_r_univariate_predictor.py
Labels: enhancement

#2576 Fix: avoid automatic device detection via serialized tensors when deserializing `PyTorchPredictor`.
  src/gluonts/torch/model/predictor.py
Labels: models, bug fix, pending v0.11.x backport, torch

#2496 Consolidate `DeepNPTSEstimator`
  src/gluonts/torch/model/deep_npts/__init__.py
  src/gluonts/torch/model/deep_npts/_estimator.py
  src/gluonts/torch/model/deep_npts/_network.py
  test/torch/model/test_deep_npts.py
  test/torch/model/test_estimators.py
Labels: enhancement, BREAKING, models, torch

#2573 Improve `PandasDataset`
  docs/tutorials/data_manipulation/pandasdataframes.md.template
  src/gluonts/dataset/pandas.py
  test/dataset/test_hierarchical.py
  test/dataset/test_pandas.py
Labels: BREAKING, pr:docs-build-notebook

#2586 serde: Fix encoding of dtypes.
  src/gluonts/core/serde/np.py
  test/core/test_serde.py
Labels: pending v0.11.x backport

#2589 Fix bug with static features in `PandasDataset`
  src/gluonts/dataset/pandas.py
  test/dataset/test_pandas.py
Labels: bug fix

#2588 Fix maybe map_or/map_or_else return types.
  src/gluonts/maybe.py
Labels: bug fix

#2583 Simplify PandasDataset.
  src/gluonts/dataset/hierarchical.py
  src/gluonts/dataset/pandas.py
Labels: BREAKING

#2596 Ensure dtype on feat_time in torch DeepAR.
  src/gluonts/torch/model/deepar/estimator.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2587 Add assertion to split function ensuring valid windows
  src/gluonts/dataset/split.py
  test/dataset/test_split.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2597 Move NPTS back to `gluonts.model`
  src/gluonts/model/npts/.typesafe
  src/gluonts/model/npts/__init__.py
  src/gluonts/model/npts/_model.py
  src/gluonts/model/npts/_predictor.py
  src/gluonts/model/npts/_weighted_sampler.py
  test/model/npts/__init__.py
  test/model/npts/test_model.py
  test/model/npts/test_npts.py
Labels: pending v0.12.x backport, rollback

#2599 Fix bug with static cardinalities in `PandasDataset`
  src/gluonts/dataset/pandas.py
  test/dataset/test_pandas.py
Labels: bug fix, pending v0.12.x backport

#2604 Fix requirements following breaking change in setuptools
  requirements/requirements-arrow.txt
Labels: dev setup, pending v0.10.x backport, pending v0.11.x backport, pending v0.12.x backport

#2601 Test: Increase timeout for xgboost tests.
  .github/workflows/tests-xgboost.yaml
Labels: dev setup

#2603 Expose `weight_decay` in torch TFT estimator class
  src/gluonts/torch/model/tft/estimator.py
Labels: enhancement, pending v0.12.x backport

#2606 Add `gluonts.util.safe_extract`
  src/gluonts/dataset/repository/_gp_copula_2019.py
  src/gluonts/nursery/sagemaker_sdk/estimator.py
  src/gluonts/nursery/tsbench/src/cli/evaluations/download.py
  src/gluonts/shell/env.py
  src/gluonts/util.py
  test/test_util.py
Labels: bug fix, pending v0.10.x backport, pending v0.11.x backport, pending v0.12.x backport

#2598 Expose aggregation method in ensemble NBEATS, fix forecast shape
  src/gluonts/mx/model/n_beats/_ensemble.py
Labels: bug fix, pending v0.10.x backport, pending v0.11.x backport, pending v0.12.x backport
