Repository awslabs/gluonts, pull requests merged in 2023-12, with the labels that each got.

#3073 Fix Rotbaum to handle short series
  src/gluonts/ext/rotbaum/_preprocess.py
  test/ext/rotbaum/test_rotbaum_smoke.py
Labels: bug fix, pending v0.13.x backport, pending v0.14.x backport

#3077 Backports v0.14.3
  src/gluonts/ext/rotbaum/_model.py
  src/gluonts/ext/rotbaum/_predictor.py
  src/gluonts/ext/rotbaum/_preprocess.py
  test/ext/rotbaum/test_model.py
  test/ext/rotbaum/test_rotbaum_smoke.py
Labels: backport

#3017 add iTransformer multivariate forecaster
  examples/iTransformer.ipynb
  src/gluonts/torch/model/i_transformer/__init__.py
  src/gluonts/torch/model/i_transformer/estimator.py
  src/gluonts/torch/model/i_transformer/lightning_module.py
  src/gluonts/torch/model/i_transformer/module.py
  test/torch/model/test_multivariate_estimators.py
Labels: models

#3086 R: add ARIMA with exogenous regressors
  src/gluonts/ext/r_forecast/R/univariate_forecast_methods.R
  src/gluonts/ext/r_forecast/_univariate_predictor.py
  test/ext/r_forecast/test_r_multi_seasonality.py
Labels: models, new feature, pr:test-r

#3089 CI: run R tests on push
  .github/workflows/tests-r.yml
Labels: CI
