Repository awslabs/gluonts, pull requests merged in 2023-10, with the labels that each got.

#3011 Test: add assertions for split keeping item_id and info fields
  test/dataset/test_split.py
Labels: tests

#3023 Fix version range for lightning
  requirements/requirements-pytorch.txt
Labels: pending v0.14.x backport

#3022 Fix WaveNet inputs
  src/gluonts/torch/model/wavenet/estimator.py
  src/gluonts/torch/model/wavenet/lightning_module.py
  src/gluonts/torch/model/wavenet/module.py
Labels: bug fix, pending v0.14.x backport

#3030 No API docs for nursery.
  docs/Makefile
Labels: documentation, pending v0.14.x backport

#3026 Add support for Pydantic v1 and v2.
  docs/Makefile
  requirements/requirements.txt
  src/gluonts/core/component.py
  src/gluonts/core/serde/_base.py
  src/gluonts/core/serde/_dataclass.py
  src/gluonts/core/settings.py
  src/gluonts/dataset/common.py
  src/gluonts/dataset/loader.py
  src/gluonts/exceptions.py
  src/gluonts/ext/rotbaum/_types.py
  src/gluonts/model/forecast.py
  src/gluonts/model/trivial/mean.py
  src/gluonts/mx/model/estimator.py
  src/gluonts/mx/model/n_beats/_ensemble.py
  src/gluonts/mx/trainer/callback.py
  src/gluonts/mx/trainer/learning_rate_scheduler.py
  src/gluonts/pydantic.py
  src/gluonts/shell/sagemaker/train.py
  src/gluonts/shell/serve/__init__.py
  src/gluonts/shell/serve/app.py
  src/gluonts/time_feature/_base.py
  src/gluonts/torch/modules/loss.py
  src/gluonts/transform/sampler.py
  src/gluonts/zebras/schema.py
  test/core/test_serde_dataclass.py
  test/core/test_serde_flat.py
  test/core/test_settings.py
  test/ext/naive_2/test_predictors.py
  test/mx/distribution/test_mx_distribution_inference.py
  test/mx/test_mx_serde.py
  test/torch/modules/test_torch_distribution_inference.py
Labels: dependency, pending v0.14.x backport

#3038 Refactor tests for `ev.aggregations`
  test/ev/test_aggregations.py
Labels: tests
