Repository awslabs/gluonts, pull requests merged in 2023-02, with the labels that each got.

#2614 Allow ReduceLROnPlateau to track val_loss when validation set is available
  src/gluonts/torch/model/deepar/lightning_module.py
  src/gluonts/torch/model/tft/lightning_module.py
Labels: enhancement, pending v0.12.x backport

#2619 Fix: torch `PoissonOutput` scaling
  src/gluonts/torch/distributions/distribution_output.py
Labels: bug fix, torch, pending v0.12.x backport

#2620 Ignore warnings in tests.
  pyproject.toml
  setup.cfg
Labels: dev setup

#2623 Remove `dataclasses` requirement
  requirements/requirements.txt
Labels: pending v0.12.x backport

#2625 Fix installation docs, fix typos in docstrings
  docs/getting_started/install.md
  src/gluonts/core/component.py
  src/gluonts/core/settings.py
  src/gluonts/dataset/arrow/enc.py
  src/gluonts/dataset/artificial/_base.py
  src/gluonts/dataset/hierarchical.py
  src/gluonts/dataset/pandas.py
  src/gluonts/ev/aggregations.py
  src/gluonts/evaluation/_base.py
  src/gluonts/ext/rotbaum/_preprocess.py
  src/gluonts/mx/trainer/learning_rate_scheduler.py
  src/gluonts/mx/trainer/model_iteration_averaging.py
  src/gluonts/mx/util.py
  src/gluonts/torch/model/deep_npts/_network.py
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/model/mqf2/module.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/torch/model/simple_feedforward/module.py
  src/gluonts/transform/convert.py
  src/gluonts/transform/feature.py
  src/gluonts/transform/split.py
Labels: pending v0.12.x backport

#2629 Add transform.Valmap, improve transform.Chain.
  src/gluonts/mx/model/deep_factor/_estimator.py
  src/gluonts/mx/model/seq2seq/_seq2seq_estimator.py
  src/gluonts/transform/__init__.py
  src/gluonts/transform/_base.py
  src/gluonts/transform/convert.py
  test/mx/model/seq2seq/test_forking_sequence_splitter.py
  test/mx/test_transform_equals.py
  test/transform/test_transform.py
Labels: BREAKING

#2630 Implement equals for __init_passed_kwargs__.
  src/gluonts/core/component.py
  test/mx/test_transform_equals.py
Labels: bug fix

#2631 Test: Remove -v option from pytest.
  pyproject.toml
Labels: tests, dev setup

#2627 make Pytorch scaler's forward API consistent
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/modules/scaler.py
Labels: BREAKING

#2633 Fix bugs in `MeanScaler`
  src/gluonts/torch/modules/scaler.py
  test/torch/modules/test_scaler.py
Labels: bug fix, torch, pending v0.12.x backport

#2639 Add Cyclic.stream.
  src/gluonts/itertools.py
Labels: enhancement

#2645 Fix norm-freq to consider freq starts.
  src/gluonts/time_feature/_base.py
  test/time_feature/test_base.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2628 Remove torch specific Dataloader, remove `num_workers` from torch models.
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/estimator.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/torch/model/tft/estimator.py
  src/gluonts/torch/util.py
Labels: BREAKING, torch

#2646 Pass prediction inputs as dict.
  src/gluonts/model/forecast_generator.py
  src/gluonts/mx/model/predictor.py
  src/gluonts/torch/model/predictor.py
Labels: BREAKING

#2648 Fix call to `extractall`
  src/gluonts/shell/sagemaker/dyn.py
Labels: bug fix, pending v0.9.x backport, pending v0.10.x backport, pending v0.11.x backport, pending v0.12.x backport

#2591 Add wrapper for Nixtla/hierarchicalforecast
  requirements/requirements-extras-hierarchicalforecast.txt
  src/gluonts/ext/hierarchicalforecast/__init__.py
  src/gluonts/ext/hierarchicalforecast/_predictor.py
  test/conftest.py
  test/ext/hierarchicalforecast/require-packages.txt
  test/ext/hierarchicalforecast/test_predictor.py
Labels: enhancement, models, new feature

#2651 Add zebras freq/period.
  .github/workflows/style_type_checks.yml
  src/gluonts/core/serde/np.py
  src/gluonts/zebras/.typesafe
  src/gluonts/zebras/__init__.py
  src/gluonts/zebras/_freq.py
  src/gluonts/zebras/_period.py
  test/zebras/test_period.py
Labels: new feature

#2659 Add `hierarchicalforecast` to github workflows.
  .github/workflows/tests-nixtla.yaml
  requirements/requirements-extras-hierarchicalforecast.txt
  test/ext/hierarchicalforecast/require-packages.txt
Labels: tests, dev setup

#2632 Simplify scalers, move to `gluonts.torch.scaler`
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/model/tft/module.py
  src/gluonts/torch/scaler.py
  test/torch/test_scaler.py
Labels: BREAKING, torch

#2642 Add Wiki 2000 dataset
  src/gluonts/dataset/repository/_gp_copula_2019.py
  src/gluonts/dataset/repository/datasets.py
Labels: new feature

#2663 Faster index building in PandasDataset
  src/gluonts/dataset/pandas.py
Labels: enhancement, pending v0.11.x backport, pending v0.12.x backport

#2665 Speed up `PandasDataset.from_long_dataframe`
  src/gluonts/dataset/pandas.py
Labels: enhancement, pending v0.11.x backport, pending v0.12.x backport

#2660 Delay instantiation of ```ScipyStudentT``` object
  src/gluonts/torch/distributions/studentT.py
  test/torch/distribution/test_studentt.py
Labels: bug fix, pending v0.12.x backport

#2658 Add test for torch models tracing
  test/torch/model/test_jit.py
Labels: tests, torch

#2670 Fix ```DateSplitter``` when split date is before start
  src/gluonts/dataset/split.py
  test/dataset/test_split.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2669 Fix r-forecast doc strings
  src/gluonts/ext/r_forecast/_hierarchical_predictor.py
  src/gluonts/ext/r_forecast/_predictor.py
  src/gluonts/ext/r_forecast/_univariate_predictor.py
Labels: documentation, pending v0.12.x backport

#2671 Remove creation of ragged sequences in `MultivariateGrouper`
  src/gluonts/dataset/multivariate_grouper.py
Labels: bug fix, pending v0.11.x backport, pending v0.12.x backport

#2680 Remove `TimeSeriesSlice`
  src/gluonts/dataset/split.py
  test/dataset/test_split.py
Labels: BREAKING

#2682 Add `itertools.power_set`
  src/gluonts/itertools.py
  test/test_itertools.py
Labels: new feature

#2681 Allow `axis` to be a tuple in `ev.aggregations`
  src/gluonts/ev/aggregations.py
  test/ev/test_aggregations.py
Labels: enhancement

#2683 Add doctests.
  .github/workflows/doctests.yaml
  src/gluonts/core/settings.py
  src/gluonts/dataset/schema/translate.py
  src/gluonts/time_feature/holiday.py
Labels: documentation, tests

#2684 Add model.Input.
  src/gluonts/model/__init__.py
  src/gluonts/model/inputs.py
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/deepar/lightning_module.py
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/model/mqf2/lightning_module.py
  src/gluonts/torch/model/simple_feedforward/module.py
  src/gluonts/torch/model/tft/lightning_module.py
  src/gluonts/torch/model/tft/module.py
  test/torch/model/test_jit.py
  test/torch/model/test_modules.py
Labels: BREAKING

#2685 Export torch models in `torch` module directly.
  src/gluonts/torch/__init__.py
  src/gluonts/torch/model/__init__.py
Labels: enhancement

#2686 Remove FallbackPredictor.
  src/gluonts/model/predictor.py
  src/gluonts/model/trivial/constant.py
  src/gluonts/model/trivial/mean.py
Labels: BREAKING

#2687 Roll back MQF2 import
  src/gluonts/torch/__init__.py
Labels: pr:docs-build-notebook, rollback

#2688 Move model init to lightning module.
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/deepar/lightning_module.py
  src/gluonts/torch/model/mqf2/estimator.py
  src/gluonts/torch/model/mqf2/lightning_module.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/torch/model/simple_feedforward/lightning_module.py
  src/gluonts/torch/model/tft/estimator.py
  src/gluonts/torch/model/tft/lightning_module.py
  test/torch/model/test_deepar_modules.py
  test/torch/model/test_mqf2_modules.py
  test/torch/model/test_tft.py
Labels: BREAKING

#2696 Fix `ev.seasonal_error`
  src/gluonts/ev/ts_stats.py
Labels: bug fix, pending v0.12.x backport
