Repository awslabs/gluonts, pull requests merged in 2023-09, with the labels that each got.

#2991 Adjust rotbaum requirements
  requirements/requirements-rotbaum.txt
Labels: dependency

#2988 Remove Python 3.7 from workflows
  .github/workflows/docs.yml
  .github/workflows/mxnet_nightly.yml
  .github/workflows/pypi.yml
  .github/workflows/style_type_checks.yml
  .github/workflows/test_release_unix_nightly.yml
  .github/workflows/test_release_win32_nightly.yml
  .github/workflows/tests-torch.yml
  .github/workflows/tests-xgboost.yaml
  .github/workflows/tests.yml
Labels: CI

#2994 Fix edge case in `PyTorchPredictor.deserialize`
  src/gluonts/torch/model/predictor.py
Labels: bug fix, torch

#2999 Use fetch tag in checkout action.
  .github/workflows/pypi.yml
Labels: CI

#2986 [shell] make ForecastConfig freq attribute explicit
  src/gluonts/shell/serve/app.py
Labels: enhancement

#2996 Add `auto` device for `PyTorchPredictor`
  src/gluonts/torch/model/d_linear/estimator.py
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/lag_tst/estimator.py
  src/gluonts/torch/model/patch_tst/estimator.py
  src/gluonts/torch/model/predictor.py
  src/gluonts/torch/model/simple_feedforward/estimator.py
  src/gluonts/torch/model/tft/estimator.py
  src/gluonts/torch/model/wavenet/estimator.py
  src/gluonts/torch/util.py
Labels: enhancement, new feature, torch

#3000 Fix `device` in torch tutorial
  docs/tutorials/advanced_topics/howto_pytorch_lightning.md.template
Labels: documentation, pr:docs-build-notebook

#3001 Shell: change server from gunicorn to waitress
  .github/workflows/style_type_checks.yml
  requirements/requirements-extras-shell.txt
  src/gluonts/shell/__main__.py
  src/gluonts/shell/serve/__init__.py
  src/gluonts/testutil/shell.py
  test/shell/require-packages.txt
Labels: enhancement

#3006 Fix Forecast plot method
  requirements/requirements-docs.txt
  requirements/requirements-test.txt
  src/gluonts/model/forecast.py
Labels: bug fix, pending v0.13.x backport

#3005 Make WaveNet `forward` configurable
  src/gluonts/torch/model/wavenet/estimator.py
  src/gluonts/torch/model/wavenet/module.py
Labels: enhancement, torch

#3004 Backports v0.13.5
  src/gluonts/ext/r_forecast/_univariate_predictor.py
  src/gluonts/model/forecast.py
Labels: backport

#3010 Fix forecast docstrings, fix type issue with naive predictor
  src/gluonts/model/forecast.py
  src/gluonts/model/seasonal_naive/.typesafe
  src/gluonts/model/seasonal_naive/_predictor.py
Labels: enhancement, pending v0.13.x backport

#3009 Remove freq attribute from NPTS
  src/gluonts/model/npts/_predictor.py
  test/model/npts/test_npts.py
Labels: API change, BREAKING
