Repository awslabs/gluonts, pull requests merged in 2023-11, with the labels that each got.

#3037 Fix edge cases in metric computation
  src/gluonts/ev/aggregations.py
  src/gluonts/ev/metrics.py
  test/ev/test_aggregations.py
  test/ev/test_metrics.py
Labels: bug fix, pending v0.13.x backport, pending v0.14.x backport

#3043 Add `plt.show()` to README
  README.md
Labels: pending v0.14.x backport

#3052 Fix mypy checks
  src/gluonts/model/evaluation.py
  src/gluonts/mx/model/deepstate/issm.py
Labels: pending v0.13.x backport, pending v0.14.x backport

#3051 ev: Batch data for faster evaluation.
  src/gluonts/model/evaluation.py
Labels: enhancement, BREAKING

#3060 Fix `iterable.Cached`.
  src/gluonts/itertools.py
  test/test_itertools.py
Labels: pending v0.14.x backport

#3061 Torch: Remove double caching of dataset.
  src/gluonts/torch/model/estimator.py
Labels: pending v0.14.x backport
