Repository awslabs/gluonts, pull requests merged in 2023-05, with the labels that each got.

#2789 Add `fourier.arima` for long seasonal time series
  src/gluonts/ext/r_forecast/R/univariate_forecast_methods.R
  src/gluonts/ext/r_forecast/_univariate_predictor.py
  test/ext/r_forecast/test_r_multi_seasonality.py
Labels: pr:test-r

#2831 Move notebook compilation logic to docs workflow
  .github/workflows/docs.yml
  Justfile
  docs/md2ipynb.py
Labels: dev setup

#2836 Fix bug in docs workflow
  .github/workflows/docs.yml
Labels: dev setup

#2841 Fix torch DeepAREstimator in case `context_length=1`
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/util.py
  test/torch/model/test_estimators.py
Labels: bug fix, pending v0.12.x backport

#2830 Simplify univariate R wrapper
  src/gluonts/ext/r_forecast/R/univariate_forecast_methods.R
  src/gluonts/ext/r_forecast/__init__.py
  src/gluonts/ext/r_forecast/_hierarchical_predictor.py
  src/gluonts/ext/r_forecast/_predictor.py
  src/gluonts/ext/r_forecast/_univariate_predictor.py
  src/gluonts/ext/r_forecast/util.py
  test/ext/r_forecast/test_r_multi_seasonality.py
  test/ext/r_forecast/test_r_univariate_predictor.py
  test/ext/r_forecast/test_r_util.py
Labels: BREAKING, pr:test-r

#2847 Ignore hidden files in FileDataset by default.
  src/gluonts/dataset/common.py
Labels: enhancement, pending v0.12.x backport

#2849 Zebras: handling of weekday offsets.
  src/gluonts/zebras/_freq.py
  src/gluonts/zebras/_period.py
  test/zebras/test_period.py
Labels: new feature

#2850 Backports for v0.12.8
  src/gluonts/core/serde/pd.py
  src/gluonts/dataset/common.py
  src/gluonts/model/forecast.py
  src/gluonts/torch/model/deepar/module.py
  src/gluonts/torch/model/estimator.py
  src/gluonts/torch/util.py
  test/torch/model/test_estimators.py
Labels: backport

#2860 Cache groupby result in `PandasDataset`
  src/gluonts/dataset/pandas.py
Labels: enhancement, performance improvement

#2864 Simplify plotting of forecasts.
  src/gluonts/model/forecast.py
Labels: BREAKING

#2870 Docs: Fix black formatting of % instructions.
  docs/md2ipynb.py
Labels: documentation, pending v0.13.x backport

#2869 Docs: Fix and simplify tutorials.
  docs/tutorials/advanced_topics/howto_pytorch_lightning.md.template
  docs/tutorials/advanced_topics/hp_tuning_with_optuna.md.template
  docs/tutorials/data_manipulation/pandasdataframes.md.template
  docs/tutorials/forecasting/extended_tutorial.md.template
  docs/tutorials/forecasting/quick_start_tutorial.md.template
Labels: documentation, pr:docs-build-notebook, pending v0.13.x backport

#2873 Update action to configure AWS credentials
  .github/workflows/docs.yml
Labels: pending v0.13.x backport

#2871 Add feat_static_cat for TSF datasets
  src/gluonts/dataset/repository/_tsf_datasets.py
  test/mx/model/deepstate/test_using_tsf_dataset.py
Labels: enhancement, datasets, pending v0.13.x backport

#2874 Docs: Use torch DeepAR in README.
  README.md
Labels: documentation, pending v0.13.x backport

#2868 0.13 backports
  .github/workflows/docs.yml
  README.md
  docs/conf.py
  docs/md2ipynb.py
  docs/tutorials/advanced_topics/howto_pytorch_lightning.md.template
  docs/tutorials/advanced_topics/hp_tuning_with_optuna.md.template
  docs/tutorials/data_manipulation/pandasdataframes.md.template
  docs/tutorials/forecasting/extended_tutorial.md.template
  docs/tutorials/forecasting/quick_start_tutorial.md.template
  src/gluonts/dataset/pandas.py
  src/gluonts/dataset/repository/_tsf_datasets.py
  src/gluonts/itertools.py
  src/gluonts/model/forecast.py
  src/gluonts/zebras/_base.py
  src/gluonts/zebras/_period.py
  src/gluonts/zebras/_time_frame.py
  src/gluonts/zebras/_time_series.py
  test/mx/model/deepstate/test_using_tsf_dataset.py
  test/test_itertools.py
  test/zebras/test_timeframe.py
Labels: pr:docs-build-notebook, backport

#2885 Fix default scale in torch DeepAR
  src/gluonts/torch/model/deepar/estimator.py
  src/gluonts/torch/model/deepar/module.py
Labels: bug fix, pending v0.13.x backport

#2894 Fix NaNs in seasonal error
  src/gluonts/model/evaluation.py
  test/model/test_evaluation.py
Labels: bug fix, pending v0.13.x backport

#2893 Mask loss in Transformer
  src/gluonts/mx/model/transformer/_network.py
Labels: enhancement
