Repository awslabs/gluonts, pull requests merged in 2023-06, with the labels that each got.

#2900 Rework `maybe.Maybe` to use a boxed container.
  src/gluonts/dataset/pandas.py
  src/gluonts/maybe.py
Labels: BREAKING

#2895 Port WaveNet to PyTorch
  docs/getting_started/models.md
  src/gluonts/torch/__init__.py
  src/gluonts/torch/model/wavenet/__init__.py
  src/gluonts/torch/model/wavenet/estimator.py
  src/gluonts/torch/model/wavenet/lightning_module.py
  src/gluonts/torch/model/wavenet/module.py
  test/torch/model/test_estimators.py
Labels: enhancement, torch

#2906 Define `__repr__` instead of `__str__` for `PandasDataset`
  src/gluonts/dataset/pandas.py
Labels: enhancement, pending v0.13.x backport

#2907 Fix typo in background.md
  docs/getting_started/background.md
Labels: documentation, pending v0.13.x backport

#2908 Fix another typo in background.md
  docs/getting_started/background.md
Labels: documentation, pending v0.13.x backport

#2905 Filter unused fields during inference
  src/gluonts/torch/model/deep_npts/_estimator.py
  src/gluonts/torch/model/predictor.py
  test/torch/model/test_estimators.py
Labels: enhancement, pending v0.13.x backport

#2912 Backports for 0.13.2
  docs/getting_started/background.md
  src/gluonts/dataset/pandas.py
  src/gluonts/model/evaluation.py
  src/gluonts/torch/model/deep_npts/_estimator.py
  src/gluonts/torch/model/predictor.py
  test/model/test_evaluation.py
  test/torch/model/test_estimators.py
Labels: backport

#2914 Rework ev.
  src/gluonts/ev/__init__.py
  src/gluonts/ev/evaluator.py
  src/gluonts/ev/metrics.py
  test/ev/test_metrics_compared_to_previous_approach.py
Labels: BREAKING

#2915 Set `accelerator="auto"` by default in lightning estimators
  src/gluonts/torch/model/estimator.py
Labels: enhancement

#2917 Add `RandomYield` to `itertools`.
  src/gluonts/itertools.py
  test/test_itertools.py
Labels: enhancement

#2921 Add scaled quantile loss
  src/gluonts/ev/__init__.py
  src/gluonts/ev/metrics.py
  src/gluonts/ev/stats.py
  test/ev/test_stats.py
  test/model/test_evaluation.py
Labels: new feature

#2925 Fix JsonLinesFile slicing.
  src/gluonts/dataset/jsonl.py
  test/dataset/test_jsonl.py
Labels: bug fix, pending v0.13.x backport

#2924 Add `gluonts.itertools.Chain`
  src/gluonts/itertools.py
  test/test_itertools.py
Labels: enhancement

#2926 Add splitting for Arrow based files.
  src/gluonts/dataset/arrow/file.py
  test/dataset/test_arrow.py
Labels: enhancement

#2923 add num_evaluations to metrics
  src/gluonts/ev/__init__.py
  src/gluonts/ev/metrics.py
  src/gluonts/ev/stats.py
  src/gluonts/evaluation/_base.py
  src/gluonts/evaluation/metrics.py
Labels: enhancement

#2928 `gluonts.ev`: Rework exports.
  src/gluonts/ev/__init__.py
  src/gluonts/model/evaluation.py
  test/ev/test_aggregations.py
  test/ev/test_metrics_compared_to_previous_approach.py
  test/ev/test_stats.py
  test/model/test_evaluation.py
Labels: BREAKING

#2930 `gluonts.ev`: add `MAE`, add tests
  src/gluonts/ev/metrics.py
  test/ev/__init__.py
  test/ev/test_metrics.py
Labels: enhancement, tests

#2932 Remove `freq` argument in `SeasonalNaivePredictor`
  src/gluonts/model/seasonal_naive/_predictor.py
  test/ev/test_metrics_compared_to_previous_approach.py
  test/ext/naive_2/test_predictors.py
  test/model/seasonal_naive/test_seasonal_naive.py
  test/model/test_evaluation.py
Labels: BREAKING

#2938 Zebras: Fix index handling of SplitFrame.resize.
  src/gluonts/zebras/_split_frame.py
Labels: bug fix, pending v0.13.x backport
