Repository awslabs/gluonts, pull requests merged in 2024-05, with the labels that each got.

#3176 Rotbaum: turn to json-based serialization
  src/gluonts/ext/rotbaum/_predictor.py
Labels: BREAKING

#3182 Tests: xfail test for `fourier.arima.xreg`
  test/ext/r_forecast/test_r_univariate_predictor.py
Labels: tests, pr:test-r

#3180 Add model card from PR 2748
  docs/getting_started/models.md
Labels: documentation

#3186 Fix incorrect input routing for models
  src/gluonts/model/forecast_generator.py
Labels: bug fix, pending v0.14.x backport, pending v0.15.x backport

#3189 Enable QuantileOutput for TiDE model
  src/gluonts/torch/distributions/distribution_output.py
  src/gluonts/torch/distributions/output.py
  src/gluonts/torch/distributions/quantile_output.py
  src/gluonts/torch/model/tide/estimator.py
  src/gluonts/torch/model/tide/module.py
  test/torch/model/test_estimators.py
Labels: enhancement, pending v0.15.x backport

#3188 Docs: fix custom pytorch model tutorial
  docs/tutorials/advanced_topics/howto_pytorch_lightning.md.template
  src/gluonts/model/forecast_generator.py
Labels: documentation, pr:docs-build-notebook, pending v0.15.x backport

#3191 Backports v0.15.1 (reprise)
  docs/tutorials/advanced_topics/howto_pytorch_lightning.md.template
  src/gluonts/model/forecast_generator.py
  src/gluonts/torch/distributions/distribution_output.py
  src/gluonts/torch/distributions/output.py
  src/gluonts/torch/distributions/quantile_output.py
  src/gluonts/torch/model/tide/estimator.py
  src/gluonts/torch/model/tide/module.py
  test/torch/model/test_estimators.py
Labels: pr:docs-build-notebook, backport
